🗃️ Add Participant Prisma schema to Consent DAS
OHCRN/platform pull request #101
Opened 2023-09-25 14:13 UTC by alyssadsouza

- Created the (updated) Participant Prisma schema with updated seed data and CRUD operations
- Also added and tested the router endpoints for Participant, Consent Question, and Participant Response CRUD operations
  - Included basic error handling
  - Added basic JSDoc comments

2023-09-27 15:52 UTC, joneubank commented on apps/consent-das/src/routers/participantResponses.ts
> +		if ((error as ErrorCallback).name == 'PrismaClientValidationError') {
While the code here is going to work, from a strictly TS safe standpoint there are a couple issue here:

The type of `error` is `unknown`, so we need to do more validation upfront before interacting with it. if `error` is undefined (from a `throw undefined` which is not something we'll add but is theoretically possible) then `error.name` will break, throwing a server error from inside your catch block.

You can more thoroughly validate this with `if(error && 'name' in error && error.name === 'PrismaClientValidationError')`

Note this doesn't confirm for us that it has the other properties of a `PrismaClientValdiationError`, so you may also need to have a checker for those.

Yes this is cumbersome, this is a consequence of how JS lets you throw absolutely anything. This is why using throw logic is quite tricky overall :(

2023-09-27 16:24 UTC, anncatton requested changes
Lots of good stuff here @alyssadsouza ! Glad you're looking at error handling already 🙂 
A lot of my feedback is gonna involve separate prs (swagger, typed errors, absolute imports) but I think what we can do here is hone down the changes a little to known fixes, and we'll discuss the separate tasks with the team - esp the error handling as I think it'll be worthwhile to think about what types of errors we're dealing with at different layers of the backend.

2023-09-27 16:24 UTC, anncatton commented on apps/consent-das/src/routers/participantResponses.ts
> +router.get('/all/:participantId/:consentQuestionId', async (req, res) => {
i'm going to suggest for these 2 `GET` endpoints that we only need one with a sort option. the mapper/api layers can then have additional logic to either return the whole list, or the latest response
i also want to rename this path but i'm not exactly sure what makes the most sense, i will give it a little extra thought!

2023-09-27 16:24 UTC, anncatton commented on apps/consent-das/src/routers/participantResponses.ts
> +		if ((error as ErrorCallback).name == 'PrismaClientValidationError') {
After talking to @joneubank , let's add a super simple error handler on the router as a catch all for now, and we can discuss/implement custom (and typed) error handling in another ticket.

It can be added on the express app in the main `index.ts` file like `app.use(errorHandler);`
This is the example in the variant-indexer repo:
 https://github.com/EUCANCan-Federated-Data-Portal/variant-indexer/blob/main/src/middleware/errorHandler.ts

But all it needs to do for now is return a `500` error! We can leave in the try/catches so that structure is still there, but can remove the if/elses for the different error types.

2023-09-27 18:40 UTC, alyssadsouza commented on apps/consent-das/src/routers/participantResponses.ts
> +router.get('/all/:participantId/:consentQuestionId', async (req, res) => {
so to clarify, we don't need an optional `submittedAt` parameter to get a response at the specified date anymore?

2023-09-28 14:54 UTC, anncatton commented on apps/consent-das/prisma/schema.prisma
> +  registrantIdVerified             Boolean?
@mistryrn is on board with `isGuardian` so please proceed!

2023-09-28 15:33 UTC, anncatton reviewed
Just adding some links to additional tickets for reference on this pr.

For moving the error handler into its own package, I'm open to doing the change here or in a separate PR. Re-request a review when you're ready!

2023-09-28 15:33 UTC, anncatton commented on apps/consent-das/src/index.ts
> +	app.use('/consent-questions', ConsentQuestionRouter);
Just adding the [ticket link](https://github.com/OHCRN/platform/issues/116) here for reference on this PR

2023-09-28 15:33 UTC, anncatton commented on apps/consent-das/src/routers/consentQuestions.ts
> +import logger from '../logger';
Ticket created for this https://github.com/OHCRN/platform/issues/117

2023-09-28 15:33 UTC, anncatton commented on apps/consent-das/src/errorHandler.ts
> +function errorHandler(err: unknown, _req: Request, res: Response, next: NextFunction): any {
My bad, can you move this up to be a package utility like the `logger`? But no need to add in the other express routers yet, we can add it as those apps get worked on!

If you prefer, we can do this in a separate PR

2023-09-29 14:36 UTC, mistryrn commented on apps/consent-das/src/routers/consentQuestions.ts
> +	logger.info('GET /consent-questions');
@alyssadsouza sorry to jump in here late (and to conflict with what @anncatton suggested 😅 ) but for now can we leave these logs in and leave them at log level `INFO`?

When we start doing things end-to-end (especially once we get auth involved), we'll want logs on operations performed in the DASes for Auditing purposes. I agree that `INFO` probably isn't the right log level here, maybe we'll add an `AUDIT` level down the line, but for now let's leave these in and as `INFO` for consistency across the DASes and Data Mapper. It'll just make it easier to Shift+CMD+F and Find All when we get a clear picture of how we want to handle the Auditing

2023-09-29 19:22 UTC, mistryrn requested changes
This is looking great! Noticed something I missed when reviewing the previous DAS PRs, sorry to request another change but this will improve the clarity of which ID is required when calling any of the DAS functions down the line 🙏

2023-09-29 19:22 UTC, mistryrn commented on apps/consent-das/src/service/search.ts
> +export const getParticipant = async (id: string): Promise<Participant> => {
## TL;DR
Sorry to request another change @alyssadsouza , but after chatting with Ann I think for clarity we'd like to still use `entityId` when referring to an entity's `id`  in function calls. There's gonna be a lot of different IDs floating around the platform, this will just make it clear when making a function call exactly which ID you need to provide.

Do you mind updating all the functions and function calls to use `entityId` (i.e. `participantId` for Participant, `consentQuestionId` for ConsentQuestion, etc)?

## Full Context
I know we decided that inside the tables we’re using `id` as an entity’s ID (i.e. `consentQuestion` has `id` as it’s ID), and when referenced externally we refer to it as `entityId` (i.e. `consentQuestionId` as the foreign key repping a Consent Question ID).

This is pretty standard practice, makes sense, I’m all for that. However, when we’re dealing with functions that interact with an entity, I think I’d like to call the params `entityId` to avoid confusion.

For example, in the consent-das search service we currently have:
```typescript
export const getConsentQuestion = async (id: string): Promise<ConsentQuestion> => {
	const result = await prisma.consentQuestion.findUniqueOrThrow({
		where: {
			id,
		},
	});
	return result;
};
```

Nothing wrong with that functionally, but I think I’d prefer:
```typescript
export const getConsentQuestion = async (consentQuestionId: string): Promise<ConsentQuestion> => {
	const result = await prisma.consentQuestion.findUniqueOrThrow({
		where: {
			id: consentQuestionId,
		},
	});
	return result;
};
```

This way the VSCode TypeScript helper will show `getConsentQuestion(consentQuestionId: string)` and it’s very clear which ID to use when calling the function.

2023-09-29 19:25 UTC, alyssadsouza commented on apps/consent-das/src/service/search.ts
> +export const getParticipant = async (id: string): Promise<Participant> => {
makes sense! I'll update that now

2023-09-29 19:46 UTC, mistryrn commented on apps/consent-das/src/routers/consentQuestions.ts
>  	const { id, isActive, category } = req.body;
Can we also update the routers to expect the `id` as `entityId`? For example, with this route:

```suggestion
	const { consentQuestionId, isActive, category } = req.body;
```

2023-09-29 19:46 UTC, mistryrn commented on apps/consent-das/src/routers/consentQuestions.ts
> +		const question = await createConsentQuestion({ consentQuestionId: id, isActive, category });
And then this line would become:

```suggestion
		const question = await createConsentQuestion({ consentQuestionId, isActive, category });
```

2023-09-29 19:46 UTC, mistryrn commented on apps/consent-das/src/routers/consentQuestions.ts
> +		const question = await createConsentQuestion({ consentQuestionId: id, isActive, category });
(I suppose the Postman collection might need updating after this too) 🙈

2023-09-29 19:50 UTC, alyssadsouza commented on apps/consent-das/src/routers/consentQuestions.ts
>  	const { id, isActive, category } = req.body;
do you want the request bodies updated too?

2023-09-29 19:50 UTC, alyssadsouza commented on apps/consent-das/src/routers/consentQuestions.ts
>  	const { id, isActive, category } = req.body;
oh I'm blind haha never mind

2023-10-02 13:03 UTC, anncatton requested changes
Sorry @alyssadsouza just a few more tidbits of feedback 😅 , and a couple thoughts for you and @mistryrn for future work on validation (that don't need answering here 😛 )

2023-10-02 13:54 UTC, anncatton approved these changes
Thanks for all this great work @alyssadsouza ! I'm approving, but let's make sure @mistryrn is all good with this before merging

2023-10-02 13:54 UTC, anncatton commented on apps/consent-das/src/routers/consentQuestions.ts
> +			res.status(400).send({ error: 'Error retrieving consent questions' });
Just change the 400 message to match the what you have in your jsdoc! 🙂

2023-10-02 14:42 UTC, mistryrn approved these changes
🚀

2023-10-02 14:44 UTC, merged