✨💄 notifications
OHCRN/platform pull request #115
Opened 2023-09-28 13:57 UTC by samrichca

2023-09-28 17:21 UTC, samrichca commented on apps/consent-ui/src/app/[lang]/dashboard/index.tsx
> +			<Notification
example implementation, not to be merged

2023-09-28 17:24 UTC, samrichca commented on apps/consent-ui/src/components/Notification/index.tsx
> +const Notification = ({
functionality for action button & dismiss button is not implemented since I don't know how exactly notifications will be used

2023-09-28 17:27 UTC, samrichca commented on apps/consent-ui/tailwind.config.js
>  import colors from './src/theme/colors';
only change is spaces -> tabs

2023-09-28 21:12 UTC, alyssadsouza requested changes
Just a couple of comments for maintaining consistency in the Icons. Thanks for adding the copyrights! 😅

2023-09-28 21:12 UTC, alyssadsouza commented on apps/consent-ui/src/components/Notification/Notification.module.scss
> +	padding: 12px 16px 24px;
as an example, the dismiss button with px:
(normal font)
![Screenshot 2023-09-28 at 5 03 49 PM](https://github.com/OHCRN/platform/assets/70766739/fe8a840c-ffac-49b6-98e1-8bd25f44365f)
(very large font)
![Screenshot 2023-09-28 at 5 04 00 PM](https://github.com/OHCRN/platform/assets/70766739/57f746c5-1784-4f73-a0c4-1764648e7172)

and with rem:
(normal font)
![Screenshot 2023-09-28 at 5 02 44 PM](https://github.com/OHCRN/platform/assets/70766739/0dacb878-d311-4805-83e3-4e899f223e98)
(very large font)
![Screenshot 2023-09-28 at 5 02 22 PM](https://github.com/OHCRN/platform/assets/70766739/47cedeb9-21af-4964-aede-b97b8aaaa4e2)

2023-09-29 20:21 UTC, samrichca commented on apps/consent-ui/src/components/Icons/CheckmarkCircle.tsx
> +			<g clip-path="url(#clip0_34_3952)">
really handy tool, thanks

2023-09-29 20:29 UTC, samrichca commented on apps/consent-ui/src/components/Notification/ActionButton.tsx
> +import { PropsWithChildren } from 'react';
I just remembered we shouldn't use it because it makes children optional. `children: ReactNode` is the way to go (usually)

2023-09-29 20:33 UTC, samrichca commented on apps/consent-ui/src/components/Notification/Notification.module.scss
> +	padding: 12px 16px 24px;
thanks for pointing this out, functional & legible elements should be in REM for scaling

2023-10-02 05:36 UTC, ciaranschutte commented on apps/consent-ui/src/components/Notification/ActionButton.tsx
> +import { PropsWithChildren } from 'react';
💯

2023-10-02 18:57 UTC, alyssadsouza reviewed
Thanks for updating the other icons, just the Close/DismissButton too!

2023-10-02 18:57 UTC, alyssadsouza commented on apps/consent-ui/src/components/Icons/Close.tsx
> +			width="23"
could you remove the fixed width/height for this icon too?

2023-10-05 18:12 UTC, alyssadsouza approved these changes
Looks good! 👍

2023-10-05 18:33 UTC, merged