🗃️ #79: add clinical profile schema to PHI-DAS
OHCRN/platform pull request #129
Opened 2023-10-06 16:46 UTC by samrichca

- add clinical profile schema to PHI-DAS

2023-10-12 19:35 UTC, mistryrn submitted a review, later dismissed
Looks good!

2023-10-12 19:35 UTC, mistryrn commented on apps/phi-das/prisma/seed/seed-data.ts
> +		// both gender fields skipped
Thanks for adding these descriptions to the seed data!

2023-10-12 20:10 UTC, alyssadsouza requested changes
Looks good! Could you add the labels for the enums in the `consent-ui` too? 🙏

2023-10-13 19:49 UTC, samrichca commented on apps/phi-das/prisma/schema.prisma
> +  UNKNOWN
this I am not sure about 🤔

2023-10-13 19:50 UTC, samrichca commented on apps/phi-das/prisma/schema.prisma
> +enum Ancestry {
don't be sorry at all, this is a good idea! I'll add them

2023-10-13 20:09 UTC, samrichca commented on apps/phi-das/prisma/schema.prisma
> +enum Ancestry {
excel/google sheets does string concatenations btw 🤓

2023-10-13 20:37 UTC, samrichca commented on apps/phi-das/prisma/schema.prisma
> +  UNKNOWN
resolved on slack, keeping as an enum

2023-10-13 21:08 UTC, mistryrn reviewed
Looks good! Just one comment now that I see how big the `common.json` file is getting.

Fortunately Ann is back on Monday and I know she had some thoughts on the i18n locale organization stuff. I'd want to hear her thoughts before splitting up that common file, just in case she was planning something already 🙏

2023-10-13 21:08 UTC, mistryrn commented on apps/consent-ui/src/i18n/locales/en/common.json
Thanks for adding the i18n labels for these! Now that I see it all in one file, I feel like it may be a good time to part out some of the `common` namespace before it gets too big.

Maybe we should create namespaces (JSON file + updating line 22 in `i18n/types/dictionaries.ts`) corresponding to the enums? That would take us from just `common`, to:
- common
- consentCategory
- consentGroup
- province
- ancestry
- ...etc

Open to suggestions, I'm not sure that's the right solution here but I am concerned with the growing size of the `common.json` files

2023-10-16 14:41 UTC, anncatton commented on apps/consent-ui/src/i18n/locales/en/common.json
thanks for bringing this up @mistryrn ! you're right, the `common` file was just a catchall for when i was doing the POC work for translations. i'll take a quick gander at what we've got in there now compared with the other dictionaries and see what might make sense for organizing going forward.

2023-10-16 15:51 UTC, anncatton commented on apps/consent-ui/src/i18n/locales/en/common.json
So my thought here is to organize these based on the components they’re used in, so that we can import specific dictionaries in specific places - i.e. like we have the `footer` dictionary imported in the `Footer` component, `header` dictionary in `Header` etc. We also have the option to import multiple dictionaries in one component, such as
 
```
const translateFromDictionaryOne = await getTranslation(currentLang, 'dictionary-one');
const translateFromDictionaryTwo = await getTranslation(currentLang, 'dictionary-two');
```
But i think the goal can be to keep this to a minimum, and maybe this approach can be what guides us in what dictionary files we create. So we could start adding dictionaries per page/component:

`clinician-registration`
`consent-step-1`
`consent-step-2`
`dashboard`

and keep `footer` , `header`, `landing-page` and so on.

I do agree with @mistryrn 's suggestion to split out some of these enums into their own dictionaries just because they'll get unwieldy, even if they are used in just one component. And they could still be imported as in the above multiple import example.

I imagine there will be some common bits of text that will be reused on various pages/components, and perhaps those are items we can put in a `common` dictionary, but we can map those out as we come to them. Also keep in mind some of the values i added previously (for page titles etc) were just for demo purposes, they may not be needed.

Another change I'd like to make - and not for this pr, it's just a task i have in mind that should be handled separately: i want to convert these dictionary files to `.ts` so we can get some type safety, and we'll also then be able to use our shared enum types as dictionary keys (and maybe some other types??), like:

```
[ConsentGroup.enum.ADULT_CONSENT]: 'Adult Consent (>18)'
```

2023-10-17 01:15 UTC, anncatton requested changes
Just added an additional request on the jsdocs stuff, let me know if you have any questions/thoughts on the sample pr!

2023-10-17 01:15 UTC, anncatton commented on apps/phi-das/src/routers/clinicalProfiles.ts
> + *               birthSex:
can we add the enum values for all the enum fields? To make it tidier we can add them as component schemas. i made an example pr here: https://github.com/OHCRN/platform/pull/158

swagger-jsdocs will pick up any files specified in the `api` list in the config options, however it doesn't seem to like folders so i've narrowed the paths to have file extensions - this also gives the option have multiple schema def files. as long as the yaml structure uses a  `components/schemas/ComponentName` setup it will be picked up by the `$ref`. Note that if there are any naming collisions between definition files swagger won't complain, the last defined component will just override! i think most of the enums schema defs could go in one file, but maybe we can separate `Ancestry` into its own file since it's gargantuan.

Also i tried this with json instead of yaml and got some sort of json pointer error...not sure if it was my code or jsdocs just doesn't like it...but i didn't feel like arguing with it so 😛

2023-10-17 20:53 UTC, alyssadsouza submitted a review, later dismissed
Looks good to me!

2023-10-18 13:20 UTC, mistryrn submitted a review, later dismissed

2023-10-18 16:15 UTC, anncatton reviewed
Thanks for adding the swagger schemas! Just one smol change needed there and then should be good to go

2023-10-18 16:15 UTC, anncatton commented on apps/phi-das/src/routers/swagger-schemas/definitions.yaml
> +    FamilyHistoryOfCancer:
Not necessary atm, but might be useful to create a more generic enum type for the `YES / NO / UNKNOWN` field types

2023-10-18 16:15 UTC, anncatton commented on apps/phi-das/src/routers/clinicalProfiles.ts
> + *                 required: true
You can remove the `type` and `required` definitions here since that's defined in the schemas

2023-10-20 19:34 UTC, anncatton approved these changes
woohoo, looks good to go 🚀

2023-10-20 20:24 UTC, merged