#139 - map out Consent Wizard Step 1 API
OHCRN/platform pull request #202
Opened 2023-10-30 16:26 UTC by samrichca

2023-10-31 15:58 UTC, mistryrn reviewed
Looks good! Still working on feedback for the InformedConsent data/type, but for now here's some feedback on the routes and how we can nest them

2023-10-31 15:58 UTC, mistryrn commented on apps/consent-api/src/index.ts
> +	app.use('/wizard/steps/informed-consent', InformedConsentRouter);
This works, but we can take advantage of nested routers in Express to make just a single `app.use('/wizard', WizardRouter);` in `index.ts` (after merging in Alyssa's latest changes in `develop`) instead of having one for each step.

See this gist for reference: https://gist.github.com/zcaceres/f38b208a492e4dcd45f487638eff716c

Essentially, what we can do is have:
- [ ] `consent-api/src/index.ts` uses `WizardRouter`:
  - `app.use('/wizard', WizardRouter);`
- [ ] `consent-api/src/routers/wizard.ts` uses `StepsRouter`:
  - `router.use('/steps', StepsRouter);`
- [ ] `consent-api/src/routers/steps.ts` uses `InformedConsentRouter` (and eventually the rest of the steps):
  - `router.use('/informed-consent', InformedConsentRouter);`
  
This would require:
- [x] merge latest `develop`
- [ ] remove this `app.use('/wizard/steps/informed-consent', InformedConsentRouter);` from `index.ts`
- [ ] create new `StepsRouter` at `src/routers/steps.ts`
- [ ] have `StepsRouter` use `InformedConsentRouter`
- [ ] update `WizardRouter` to use `StepsRouter`

2023-10-31 17:58 UTC, mistryrn commented
After discussing with Ann, I realized I missed giving you some important information for this ticket with regards to the `InformedConsent` type (or any of the `key: value` pairs for consent questions). Sorry about that! I think the key-value discussion happened while I was waiting for my Mac to update, so I was following along via Slack on my phone 😅 

Anyway, we actually *do* have Consent Question IDs, but at the moment they only live in the `consent-das` seed data since at the time we hadn't finalized the `types` structure. Since we have a list of the IDs, we should make an enum for them in the types library and update references to `consentQuestionId` to use that enum.

Also, in cases like this, instead of `COMPLETED_INFORMED_CONSENT: z.boolean(),` we can do `[ConsentQuestionIDs.informedConsent]: z.boolean(),` instead.

Here's the list of Consent Question IDs (from [`apps/consent-das/prisma/seed/seed-data.ts`](https://github.com/OHCRN/platform/blob/develop/apps/consent-das/prisma/seed/seed-data.ts)):
```
informed-consent__read-and-understand
release-data__clinical-and-genetic
release-data__de-identified
research-participation__future-research
research-participation__contact-information
recontact__future-research
recontact__secondary-contact
review-sign__signed
```

We'll make a separate ticket to update Prisma to use an enum for the Consent Question IDs, but for this ticket you can add one in Zod and then update your `InformedConsent` type accordingly:

- [ ] 1. Add Consent Question IDs type in Zod:
	- [ ] create `ConsentQuestionId` enum and type inside `types/src/entities/ConsentQuestion`, export these from the file as well
	- [ ] update `ConsentQuestion.id` to use that `ConsentQuestionId` as its type
	- [ ] update tests to use new `ConsentQuestionId` type
- [ ] 2. Update `InformedConsent` Type:
	- [ ] update `InformedConsent` type to use specific ID from consent question IDs enum (`informed-consent__read-and-understand`)
	- [ ] rename `InformedConsent` type to `InformedConsentBase`
	- [ ] create `InformedConsentRequest` and `InformedConsentResponse` types which extend `InformedConsentBase`
	- [ ] update POST to use `InformedConsentRequest` type
	- [ ] update GET to use `InformedConsentResponse` type
	- [ ] for GET request, return mock object that matches `InformedConsentResponse` type
	- [ ] update tests to reflect new types

We'll have a separate ticket for updating Prisma, but these changes above can all be tackled in this PR since the rest of the Consent Wizard steps will want to use the Consent Question IDs. As for the renaming to differentiate the `InformedConsentRequest` and `InformedConsentResponse` -- even though they're the same for now, this just gives us a little more flexibility in case the UI ends up needing something a little different from the GET requests down the line.

2023-11-01 15:37 UTC, mistryrn requested changes
Looks good overall, just a few change requests:
- [ ] revert `pdf` and `progress` back into `WizardRouter`
- [ ] remove comment in `consent-das` seed data

2023-11-01 15:37 UTC, mistryrn commented on packages/types/src/entities/InformedConsent.ts
Looks good, thanks for defining the `Request` and `Response` types

2023-11-01 15:37 UTC, mistryrn commented on apps/consent-das/prisma/seed/seed-data.ts
> +	// TODO change id to ConsentQuestionId.QUESTION_ID
Since we already have a ticket in progress for this you can remove this comment

2023-11-01 15:37 UTC, mistryrn commented on apps/consent-api/src/routers/pdf.ts
Ah, sorry! For individual routes like this `GET wizard/pdf` and the `GET wizard/progress` one below, we don't need to break them out into their own routers/files as it's a bit overkill here. If you don't mind, can we revert those back into the `wizard.ts` router?

2023-11-01 15:37 UTC, mistryrn commented on apps/consent-api/src/routers/progress.ts
Same comment as PDF router, let's move this back into `wizard.ts`

2023-11-01 15:37 UTC, mistryrn commented on apps/consent-api/src/routers/steps.ts
Looks good!

2023-11-01 15:57 UTC, alyssadsouza commented on apps/consent-api/src/routers/informedConsent.ts
> + *               type: object
I think you can skip this and go straight to the reference, because it looks like the response body here is just the `InformedConsentResponse` schema. So basically:
```
 *     responses:
 *       201:
 *         description: OK
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/InformedConsentRequest'
```
If you open the Swagger-UI at http://localhost:8080/api-docs you should be able to verify the response looks like:
```
{
  "INFORMED_CONSENT__READ_AND_UNDERSTAND": true
}
```
instead of:
```
{
  "data": {
    "INFORMED_CONSENT__READ_AND_UNDERSTAND": true
  }
}
```

2023-11-01 15:57 UTC, alyssadsouza commented on apps/consent-api/src/routers/informedConsent.ts
> + *               type: object
Also not sure if this should apply to the request body, depending on how we want the request body to look - do we want it to be wrapped in a `data` key?

2023-11-01 15:57 UTC, alyssadsouza commented on apps/consent-api/src/routers/informedConsent.ts
> + *                   $ref: '#/components/schemas/InformedConsentResponse'
Same as comment above

2023-11-01 21:04 UTC, mistryrn submitted a review, later dismissed
Thanks for getting all those changes in! This looks good and should be a solid blueprint for the rest of the Consent Wizard steps :)

2023-11-02 13:32 UTC, alyssadsouza requested changes
Everything else looks good to me, just add in the rest of the question IDs since we know them right now!

2023-11-02 13:32 UTC, alyssadsouza commented on packages/types/src/entities/ConsentQuestion.ts
> +const CONSENT_QUESTION_IDS = ['INFORMED_CONSENT__READ_AND_UNDERSTAND'] as const;
could you add the remaining questions IDs as well?
```
INFORMED_CONSENT__READ_AND_UNDERSTAND
RELEASE_DATA__CLINICAL_AND_GENETIC
RELEASE_DATA__DE_IDENTIFIED
RESEARCH_PARTICIPATION__FUTURE_RESEARCH
RESEARCH_PARTICIPATION__CONTACT_INFORMATION
RECONTACT__FUTURE_RESEARCH
RECONTACT__SECONDARY_CONTACT
REVIEW_SIGN__SIGNED
```

2023-11-02 14:22 UTC, alyssadsouza approved these changes
Thanks for adding all the question IDs!

2023-11-02 14:24 UTC, merged