🦺 Map out Consent Wizard - Step 2
OHCRN/platform pull request #221
Opened 2023-11-02 16:18 UTC by alyssadsouza

- Adds skeleton endpoints for GET and POST requests at `/wizard/steps/consent-to-release-data` for consent wizard step 2 page
  - Added JSDocs to document the endpoint's parameters and responses
  - Added the`ConsentReleaseDataRequest` and `ConsentReleaseDataResponse` Zod schemas to describe the request/response body

2023-11-02 16:23 UTC, alyssadsouza commented on packages/types/src/entities/ConsentReleaseData.ts
> +	[ConsentReleaseDataQuestion.enum.RELEASE_DATA__OHIP_NUMBER]: OhipNumber.optional(),
“OHIP Number” is marked in the UI as required but I'm assuming that just applies to the UI, the request body can have an undefined OHIP number if they check “don’t have an Ontario health card”. The form validation in the UI can check whether the question was responded to.

2023-11-02 17:28 UTC, samrichca commented on apps/consent-api/src/routers/consentReleaseData.ts
> +		logger.info(`Retrieved informed consent`);
change logger message to "retrieved consent to release data"

2023-11-02 18:37 UTC, samrichca commented on apps/consent-ui/src/i18n/locales/fr/consent-release-data.ts
> +const dictionary = {
maybe these keys should use the enum you have below (see the locale/en/common.ts file)

2023-11-02 18:38 UTC, alyssadsouza commented on apps/consent-ui/src/i18n/locales/fr/consent-release-data.ts
> +const dictionary = {
ah! I made the enum for that purpose and yet forgot to use it, I knew I would forget something

2023-11-02 20:55 UTC, samrichca commented on apps/consent-ui/src/i18n/locales/fr/consent-release-data.ts
> +const dictionary = {
based on what @anncatton said about only updating one service - should we update the dictionary when we build the page in consent-ui?

2023-11-03 14:18 UTC, mistryrn commented on packages/types/src/entities/ConsentReleaseData.ts
> +	[ConsentReleaseDataQuestion.enum.RELEASE_DATA__OHIP_NUMBER]: OhipNumber.optional(),
Good callout re: `OhipNumber`

We should probably get confirmation from Brandon regarding the "I don't have an Ontario health card" flow. It's been a while since we discussed it but I think the intention may have been to set it to the special `0000000000` case when someone selects that, allowing us to still meet the "required" field.

Do you mind asking Brandon about that in #ohcrn-dev ?

2023-11-03 14:59 UTC, anncatton commented on apps/consent-ui/src/i18n/locales/fr/consent-release-data.ts
> +const dictionary = {
Yes @samrichca that's def the goal! However, with the consent-api mapping work involving the schema types this kind of overlap will occur, esp since we're using enums in the dictionary keys. I think it's fine to leave those changes in here for now, they are clearly called out in the PR description. The dictionary is a somewhat special case as we don't want to miss adding values as we come across them, (and the changes often look "big" because it's just a lot of text) but perhaps going forward it could be useful to have a secondary pr that is just for dictionary modifications. I'm open to suggestions on what the team thinks is best!

2023-11-03 15:30 UTC, alyssadsouza commented
> There's also an unrelated failing test in ClinicianInvite -> looks like we forgot to add the consentToBeContacted field when that got added into the schema. That can be a separate fix tho i think - i'm not sure if that file is modified elsewhere atm

@anncatton that was fixed in `develop` in #219, that's my bad for not pulling changes from `develop`.

2023-11-03 15:38 UTC, anncatton commented
> > There's also an unrelated failing test in ClinicianInvite -> looks like we forgot to add the consentToBeContacted field when that got added into the schema. That can be a separate fix tho i think - i'm not sure if that file is modified elsewhere atm
> 
> @anncatton that was fixed in `develop` in #219, that's my bad for not pulling changes from `develop`.

aha ok awesome, thanks for verifying @alyssadsouza

2023-11-03 17:53 UTC, alyssadsouza commented on packages/types/src/entities/ConsentReleaseData.ts
> +const CONSENT_RELEASE_DATA_QUESTIONS = [
that makes sense, I'll rename this to `ConsentReleaseDataFieldName` instead of `ConsentReleaseDataQuestion` unless @mistryrn disagrees

2023-11-03 19:24 UTC, mistryrn commented on packages/types/src/entities/ConsentReleaseData.ts
> +const CONSENT_RELEASE_DATA_QUESTIONS = [
Great idea @anncatton @alyssadsouza ! Yeah let's go with `field names` for the form fields, instead of `questions`. The proposed rename sounds fine to me 👍

2023-11-05 21:25 UTC, joneubank requested changes
Lots more great work here. I found a couple items that need some review, let me know if any questions. :)

2023-11-05 21:25 UTC, joneubank commented on apps/consent-api/src/routers/consentReleaseData.ts
> + *       401:
this is out of scope for your ticket but I am writing it here so we think about it...

we need schemas for error responses, the content of the error response message should be declared in the schema and it should be consistent across requests.

2023-11-05 21:25 UTC, joneubank commented on apps/consent-api/src/routers/consentReleaseData.ts
> +		const data = ConsentReleaseDataRequest.parse(req.body);
If this parse fails then an error is thrown, we should be handling this case and communicating to the requester that the request was rejected due to invalid content. This should result in a response with status 400. The response message should ideally include information about what part of the validation failed but translating the zod parsing is a general task that needs focused work so for now just an error 400 would suffice.

We have an opportunity here to write a function to standardize handling POST request body validation, if you want we can talk about building that out quickly.

2023-11-05 21:25 UTC, joneubank commented on apps/consent-api/src/routers/consentReleaseData.ts
> +	logger.info(`GET /wizard/steps/consent-to-release-data`);
Thanks for thinking about logging. To keep all our request logging consistent and not require maintaining logger statements we should use a middleware function added to the server router that consistently logs all incoming requests and their response status.

There is a common library used for this called [morgan](https://npmjs.org/package/morgan), I'm not a huge fan of it's log formatting or the fact that it waits to log until the response is complete, but this would be a quick fix that serves our needs like 90% if you want to set that up.

In any case, we should remove this log statement.

2023-11-06 12:54 UTC, anncatton commented on packages/types/src/entities/ConsentReleaseData.ts
> +] as const;
My thought for using enums was, let's have them for consistent naming of keys, which I think comes from my experience with the form field keys and req/res types we had in dac-ui -> the type checking of keys there always felt muddled. However I see what you mean here about the unwieldiness of this, and with the zod parse option we will have that check on object keys out of the box.
However, there are some cases where I'd like to keep enums in use - the `ConsentQuestionId` here lines up with the prisma schema [enums](https://github.com/OHCRN/platform/blob/develop/apps/consent-das/prisma/schema.prisma#L52), and I like that for consistency across contexts.

Out of curiosity, is there a way to import zod enums in such a way that the enum name doesn't need to be prepended each time (i'm thinking like static imports in java)?

2023-11-06 12:58 UTC, anncatton commented on apps/consent-api/src/routers/consentReleaseData.ts
> + *       401:
This is one of those "we have a ticket for this!" cases: https://github.com/OHCRN/platform/issues/179

Error handling + custom error types has been on my mind for awhile now, this ticket is not spec'd out yet but I'd be down with getting to this sooner rather than later.

2023-11-06 13:08 UTC, anncatton commented on apps/consent-api/src/routers/consentReleaseData.ts
> +		const data = ConsentReleaseDataRequest.parse(req.body);
Generally these "map out" tasks have been to lay the groundwork for the api endpoints, but not entirely implement them, including full validation and correct error responses. That is I think where the "build <endpoint>" tickets come in. Currently @mistryrn and I are going through the existing "build" tickets to make sure they're spec'd out correctly - I would love to add in standardized post request handling, maybe we can add as part of these build tickets?

2023-11-06 13:14 UTC, anncatton commented on apps/consent-api/src/routers/consentReleaseData.ts
> +	logger.info(`GET /wizard/steps/consent-to-release-data`);
These kinds of log statements I think are part of the mapping out of the endpoints, and were not necessarily intended to be kept around (and I see as I say that, that if that's the case they shouldn't be added in the first place) tbh we need to discuss what logging would be useful in the api/dases.

2023-11-06 13:25 UTC, anncatton commented on packages/types/tests/entities/ConsentReleaseData.spec.ts
> +	it('Must provide valid fields', () => {
Yeah I don't disagree with this. We can prune these tests, but maybe we can use some of this work as reference for the unit testing needed on the api endpoints.

2023-11-06 13:37 UTC, anncatton commented on apps/consent-api/src/routers/consentReleaseData.ts
> +	logger.info(`GET /wizard/steps/consent-to-release-data`);
I should add, there's a ticket for [logging in prisma](https://github.com/OHCRN/platform/issues/177), but not for the consent-api

2023-11-06 14:16 UTC, alyssadsouza commented on packages/types/src/entities/ConsentReleaseData.ts
> +] as const;
> Out of curiosity, is there a way to import zod enums in such a way that the enum name doesn't need to be prepended each time (i'm thinking like static imports in java)?

After some googling I found that we can destructure the enum values:
```ts
const { RELEASE_DATA__FIRST_NAME } = ConsentReleaseDataFieldName.enum;
...
[RELEASE_DATA__FIRST_NAME] = 'First Name';
```

2023-11-06 16:03 UTC, joneubank commented on apps/consent-api/src/routers/consentReleaseData.ts
> +	logger.info(`GET /wizard/steps/consent-to-release-data`);
I will be satisfied with removing these log statements for now, we don't need to expand the scope of this ticket to request logging.

2023-11-06 16:04 UTC, joneubank commented on apps/consent-api/src/routers/consentReleaseData.ts
> +		const data = ConsentReleaseDataRequest.parse(req.body);
I disagree here for two reasons:
1. part of the describing or "mapping" of the endpoint should be getting the error responses correct
2. code was put in place to validate the inputs but the errors were not handled properly

We should get this right as we add in the validation code.

2023-11-08 16:43 UTC, anncatton reviewed
Thanks for cleaning up all the tests we didn't need, this is so much more readable. Just one comment about that try/catch - we can also run that past @joneubank to see if that will address his feedback about the error handling.

2023-11-08 16:43 UTC, anncatton commented on apps/consent-api/src/routers/consentReleaseData.ts
> +		try {
i think instead this should be one try/catch block - i'm not sure with this setup if the outer catch would ever be reached 🤔 . we should be able to check what is returned from the `.parse()` call by checking the `error` type in the catch block, and return a 400 if it's a ZodError, and otherwise return a 500. i'm thinking something like:
```
try {
// parse()
// return 201
} catch(error) {
if (error instanceof ZodError) {
// return 400
else {
// return 500
}
```
there'll be much more info in the ZodError object on what exactly failed to parse, but i think for the purposes of this ticket a general check is fine.

2023-11-08 17:02 UTC, alyssadsouza commented on apps/consent-api/src/routers/consentReleaseData.ts
> +		try {
hmm looks like we'll need to move zod outside of types and into the root folder to import that error

2023-11-09 16:05 UTC, anncatton approved these changes
this looks good to me, let's see if jon is also happy with it 😛

2023-11-09 16:05 UTC, anncatton commented on packages/types/src/entities/Error.ts
> +
maybe just add a comment here about why we're exporting this, and that it's just the initial portion of implementing error handling.

2023-11-09 20:52 UTC, joneubank commented on packages/types/src/entities/Error.ts
> +
Yeah, what is this about? Why wouldn't other places jsut import directly from zod?

2023-11-09 20:53 UTC, joneubank commented on apps/consent-api/src/routers/consentReleaseData.ts
> +import { ConsentReleaseDataRequest, ZodError } from 'types/entities';
Importing zod from our own module feels weird... we should be directly importing from zod, no?

2023-11-09 20:56 UTC, joneubank commented on apps/consent-api/src/routers/consentReleaseData.ts
> +		}
Glad to see this. If this pattern gets repeated a lot, as I suspect it will be, theres probably a use for a function for to do request error handling.

2023-11-09 21:01 UTC, joneubank approved these changes

2023-11-09 21:11 UTC, alyssadsouza commented on packages/types/src/entities/Error.ts
> +
copying from one of my previous comments:
>hmm looks like we'll need to move zod outside of types and into the root folder to import that error
instead of doing that, I'll add an Error.ts schema to types which we can use when we add custom schemas for error handling, and just export the zod error type from there for now

after talking with @anncatton we agreed on not moving the Zod import to the root directory for this, since it is just a temporary method for error handling. I'm guessing any Zod types like `ZodError` will be encompassed in some `Error` schema when we actually implement proper error handling, making imports from Zod here just temporary.

2023-11-09 21:12 UTC, alyssadsouza commented on packages/types/src/entities/Error.ts
> +
I'll add a comment there for clarity though

2023-11-10 14:34 UTC, anncatton approved these changes

2023-11-10 14:35 UTC, merged