#203: add consent wizard step 3 zod schema
OHCRN/platform pull request #222
Opened 2023-11-02 17:13 UTC by samrichca

2023-11-02 18:58 UTC, alyssadsouza commented on packages/types/src/entities/ConsentResearchParticipation.ts
> +export const ResearchParticipationRequestSchema: SchemaObject = generateSchema(
definitely nit picking here but should this also be prefixed with `Consent` i.e. `ConsentResearchParticipationRequestSchema`? if not then for consistency I think I should change to match this in #221.

2023-11-02 18:58 UTC, alyssadsouza commented on packages/types/tests/entities/ConsentResearchParticipation.ts
missing the `spec.ts` file extension - I ran the tests and was like ... shouldn't there be 21 tests...? 🕵️

2023-11-02 20:51 UTC, samrichca commented on packages/types/src/entities/ConsentResearchParticipation.ts
> +export const ResearchParticipationRequestSchema: SchemaObject = generateSchema(
not nitpicking at all, i thought i'd caught all of these. good eye!

2023-11-02 20:53 UTC, samrichca commented on packages/types/tests/entities/ConsentResearchParticipation.ts
23 now 🌽

2023-11-03 16:49 UTC, alyssadsouza reviewed
Looks good to me!

2023-11-03 16:55 UTC, anncatton commented on packages/types/tests/entities/ConsentResearchParticipation.spec.ts
> +				[ConsentQuestionId.enum.RESEARCH_PARTICIPATION__CONTACT_INFORMATION]: true,
thanks for the separate tests for req/res

2023-11-03 16:55 UTC, anncatton commented on apps/consent-api/src/routers/consentResearchParticipation.ts
> +		res.status(200).send({
same comment as above

2023-11-08 16:58 UTC, anncatton requested changes
Mainly commenting on the try/catch in the `POST`, same as in step 2.

2023-11-08 16:58 UTC, anncatton commented on packages/types/src/entities/ConsentResearchParticipation.ts
> +export const ConsentResearchParticipationBase = z.object({
i think you mentioned this in the step 2 PR @alyssadsouza , about destructuring the enum - do you wanna use that in these prs for the `ConsentQuestionId` keys?

2023-11-08 16:58 UTC, anncatton commented on apps/consent-api/src/routers/consentResearchParticipation.ts
> +			const data = ConsentResearchParticipationRequest.parse(req.body);
same feedback as in step 2, let's get rid of the nested try/catch and do an error type check to differentiate between a parsing error and a general "something went wrong" 500.

2023-11-08 17:02 UTC, alyssadsouza commented on packages/types/src/entities/ConsentResearchParticipation.ts
> +export const ConsentResearchParticipationBase = z.object({
yup good idea!

2023-11-09 16:16 UTC, anncatton reviewed
this looks good to me, but we'll wait on step-2 being reviewed/merged

2023-11-09 16:16 UTC, anncatton commented on packages/types/src/entities/ConsentResearchParticipation.ts
> +export const ConsentResearchParticipationBase = z.object({
🙏

2023-11-10 15:08 UTC, anncatton approved these changes
lgtm 🚀 🎸 🪨

2023-11-10 15:36 UTC, merged