#204: map out step 4
OHCRN/platform pull request #223
Opened 2023-11-02 20:56 UTC by samrichca

2023-11-03 16:56 UTC, alyssadsouza commented on packages/types/src/entities/ConsentRecontact.ts
> +	[ConsentQuestionId.enum.RECONTACT__SECONDARY_CONTACT]: z.boolean(),
this will also need to include the secondary contact info fields that we collect if they choose "Yes" to secondary contact:
<img width="701" alt="image" src="https://github.com/OHCRN/platform/assets/70766739/4df8c38c-a08b-43b8-a1b6-b68f17eaeea0">

2023-11-03 17:26 UTC, anncatton commented on apps/consent-api/src/routers/consentRecontact.ts
> +		res.status(201).send({
same feedback as in the step-3 pr: let's define these mock responses as separate vars + `TODO` so it's really obvious it's mock data

2023-11-03 17:26 UTC, anncatton commented on apps/consent-api/src/routers/consentRecontact.ts
> +			[ConsentQuestionId.enum.RECONTACT__FUTURE_RESEARCH]: true,
same as above

2023-11-03 17:26 UTC, anncatton commented on packages/types/src/entities/ConsentRecontact.ts
> +	[ConsentQuestionId.enum.RECONTACT__SECONDARY_CONTACT]: z.boolean(),
following that we'll have to add tests for this too, thanks for pointing this out @alyssadsouza 

This relates back to my comment on step 2 PR https://github.com/OHCRN/platform/pull/221#discussion_r1381829401 -> i think we should refer to these as `fieldNames` or something similar to differentiate them

2023-11-08 17:21 UTC, anncatton requested changes
Just some smol changes, as in the other step PRs 🙂

2023-11-08 17:21 UTC, anncatton commented on apps/consent-api/src/routers/consentRecontact.ts
> +		try {
same comment for this nested try/catch as in steps 2 and 3 🙂

2023-11-08 17:21 UTC, anncatton commented on packages/types/tests/entities/ConsentRecontact.spec.ts
> +	it('Must define secondary contact info if user consented to secondary contact', () => {
Following Jon's feedback in [step 2](https://github.com/OHCRN/platform/pull/221#discussion_r1382640542), can we add test descriptions for each scenario that is being tested here? i.e.:

`it('Parses correctly when secondary consent is indicated and required fields are provided')`
`it('Fails to parse when secondary consent is indicated but secondaryContactPhoneNumber is not provided')` etc etc

so that the intention of each test is very clear.

2023-11-10 16:23 UTC, anncatton approved these changes
Thanks for updating the tests + that `TODO`! 🚀

2023-11-10 16:25 UTC, merged