✨➕🚧 #186: add react-hook-form + clinician invite form
OHCRN/platform pull request #235
Opened 2023-11-07 18:48 UTC by samrichca

2023-11-13 17:06 UTC, joneubank commented on apps/consent-ui/src/components/Form/FormField/index.tsx
> +			<TextInput {...inputProps} />
Will this eventually change component used based on the prop `type`?

2023-11-13 17:08 UTC, joneubank commented on apps/consent-ui/src/components/Form/DefaultFieldSet/index.tsx
> +const DefaultFieldSet = ({
I would remove `Default` from the name. Can specify names later if we have multiple implementations that need differentiation.

2023-11-27 16:16 UTC, samrichca commented on packages/types/tests/entities/Name.spec.ts
> +		expect(Name.safeParse('').success).false;
empty strings pass some zod validation, so we should add them to unit tests when we're also testing undefined & null.

2023-11-28 15:41 UTC, justincorrigible commented on apps/consent-ui/src/i18n/locales/en/index.ts
> +	'clinician-invite-form': clinicianInviteFormDictionary,
Note: Not asking for changes.

For my own understanding, what was the reasoning for this project to deviate from the JS-idiomatic camelCase for keys/variables?

2023-11-28 15:54 UTC, joneubank commented on apps/consent-ui/src/i18n/locales/en/forms.ts
> +} satisfies Record<string, string>;
Repeat of previous comment. We want all french dictionaries to satisfy the shape of the english version of the same dictionary. This will let TS enforce that they have the same shape.

2023-11-28 15:55 UTC, joneubank commented on apps/consent-ui/src/i18n/locales/fr/form-labels.ts
> +} satisfies FormLabelsDictionary;
Like this! 👍

2023-11-28 18:15 UTC, samrichca commented on apps/consent-ui/src/i18n/locales/en/index.ts
> +	'clinician-invite-form': clinicianInviteFormDictionary,
I'm not sure actually

2023-11-28 18:20 UTC, samrichca commented on apps/consent-ui/src/components/Form/FormField/index.tsx
> +			<TextInput {...inputProps} />
the `type` just changes the type attribute in the HTML input

- email inputs use <TextFieldset type="email" /> - they work like a basic text input, but the `type` tells your browser to show an email keyboard (on mobile) and provide email options for autocomplete
- date inputs - <DateFieldset /> with a datepicker library
- checkbox inputs - <CheckboxFieldset />

2023-11-28 18:59 UTC, mistryrn reviewed
Haven't completed my review yet, but leaving a few comments for now before the meeting. Lots of good stuff so far!

2023-11-28 18:59 UTC, mistryrn commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +	const handleRecaptchaChangeDemo = () => {
Is this still for demo purposes only, or can we drop the `Demo` suffix from the function name here?

2023-11-28 18:59 UTC, mistryrn commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +		console.log('SUBMIT DATA', data);
We'll want to clean up the logs before merging, but I assume this is just for testing/dev purposes at the moment so it's fine for now.

2023-11-28 18:59 UTC, mistryrn commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +						error={errors.participantFirstName?.type && errorsDict['required']}
Noticed that these are all listed as `errors.participantFirstName?.type`, even for different fields like `participantLastName` – does it make a difference if they're all the same, or should they match up with their respective field `name` values?

2023-11-28 18:59 UTC, mistryrn commented on apps/consent-ui/src/components/Form/README.md
Thanks for adding some documentation for this! 😄 Can we move it to the root `docs` directory to keep this kind of technical documentation in the same place?

2023-11-28 21:11 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +						error={errors.participantFirstName?.type && errorsDict['required']}
fixed during demo, thanks for pointing it out!

2023-11-28 21:13 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +	const handleRecaptchaChangeDemo = () => {
removed, I'm keeping the success message as demo since it'll be replaced with a redirect to the homepage (added a comment to this effect)

2023-11-28 21:14 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +		console.log('SUBMIT DATA', data);
removed!

2023-11-29 22:24 UTC, alyssadsouza commented on packages/types/src/entities/ClinicianInvite/ClinicianInviteForm.ts
> +		clinicianTitleOrRole: z.string().trim().nonempty(),
I was looking at the docs, is `nonempty` supposed to be for `array` types? https://zod.dev/?id=nonempty I think you'll have to use `min()` here but you probably know more about this since you've been looking into the whole validating empty strings thing

2023-11-29 22:24 UTC, alyssadsouza commented on packages/types/src/entities/ParticipantIdentification.ts
> +				}).success
Shouldn't these already be validated from the schema? `.optional()` permits either `undefined` or the specified type, so checking that they're not `undefined` should mean they have the specified type right?

2023-11-29 22:26 UTC, alyssadsouza commented on packages/types/src/entities/ParticipantIdentification.ts
> +				}).success
Shouldn't these already be validated from the schema? `.optional()` permits either `undefined` or the specified type, so checking that they're not `undefined` should mean they have the specified type right?

2023-11-29 23:08 UTC, samrichca commented on apps/consent-ui/src/components/Form/fieldsets/CheckboxFieldSet/index.tsx
> +			{error && <span style={{ color: 'red' }}>{error}</span>}
I'm gonna do better styling in the form styling ticket, this is bad on purpose ;)

2023-11-29 23:08 UTC, samrichca commented on packages/types/src/entities/ClinicianInvite/ClinicianInviteForm.ts
> +		clinicianTitleOrRole: z.string().trim().nonempty(),
you're right, will change to min(1)

2023-11-29 23:12 UTC, samrichca commented on apps/consent-ui/src/components/Form/fieldsets/CheckboxFieldSet/index.tsx
> +					{required && <RequiredAsterisk />}
good point 👍

2023-11-30 15:29 UTC, anncatton commented on apps/consent-ui/src/i18n/locales/en/index.ts
> +	'clinician-invite-form': clinicianInviteFormDictionary,
that was me, i also don't remember

2023-11-30 17:04 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +			axios
any reason for limiting it to 200 originally? we'll need 201 & 204 which IIRC is allowed in axios by default

2023-11-30 17:14 UTC, samrichca commented on packages/types/src/entities/ParticipantIdentification.ts
> +				}).success
after thinking about this more, there's 3 potential outcomes

- undefined (skips non-`optional()` validation)
- defined but doesn't pass validation - short-circuits the validation, `optional()` isn't considered at all.
- defined & does pass validation

so the undefined check is fine and I'll revert to that. empty strings & whitespace are a separate issue that already has a ticket.

2023-11-30 17:41 UTC, justincorrigible commented on apps/consent-ui/src/i18n/locales/en/index.ts
> +	'clinician-invite-form': clinicianInviteFormDictionary,
Not in the scope of this PR, but sounds to me like if there's no practical necessity for deviation from best practices (e.g. a weird third-party library requirement that breaks things otherwise), it'd be best if we return these to consistent JS casing.

Thoughts?

2023-11-30 19:06 UTC, justincorrigible commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +			axios
This could be abstracted into the response validation options within the Axios client.

That's done at `validateStatus` in the config object

2023-11-30 21:32 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +			axios
removed validateStatus as discussed on slack

2023-12-01 15:37 UTC, justincorrigible commented on apps/consent-ui/src/components/Form/RequiredAsterisk/index.tsx
> +const RequiredAsterisk = ({ className }: { className?: string; required?: boolean }) => (
the props `required` is unused and can be removed

2023-12-01 16:03 UTC, justincorrigible commented on apps/consent-ui/src/components/Form/fieldsets/inputs/SelectInput.tsx
> +			onChange(typeof val === 'string' ? val : val?.value || null)
3 thoughts/questions:
1. cognitive burden: this line is quite loaded for this simple validation. It'd be easier to read (and possibly maintain) if abstracted and broken down as a switch.
2. consistency with types elsewhere: I was under the impression we wanted to use `undefined` instead of `null` for empty fields. Personally I'd prefer using nulls (difference between "field has been touched and left empty" vs "untouched field), but still, asking just to double-check for consistency.
3. consistency with types in the same file: as semi-related followup from the last point, in this line the fallback is `null`, while in line 45 the fallback is an empty string. There's likely a reason for this difference, but it isn't clear here. Should this line 41 also default to empty string instead?

2023-12-01 16:10 UTC, justincorrigible commented on apps/consent-ui/src/components/Form/fieldsets/FieldSet/index.tsx
> +			{error && <p style={{ color: 'red' }}>{error}</p>}
Not asking for change, just sharing my own practices that I've found useful:
In layouts that include multiple different children/components, I tend to add blank lines to facilitate visually parsing the layout from source.

```suggestion
			</label>

			{children}

			{error && <p style={{ color: 'red' }}>{error}</p>}
```

2023-12-01 16:38 UTC, anncatton commented on apps/consent-ui/src/i18n/locales/en/index.ts
> +	'clinician-invite-form': clinicianInviteFormDictionary,
ticket: https://github.com/OHCRN/platform/issues/289

2023-12-01 16:41 UTC, anncatton submitted a review, later dismissed
Approving, but let's have @joneubank / @justincorrigible have final approval if possible

2023-12-01 17:52 UTC, justincorrigible submitted a review, later dismissed
LGTM 👍 
Thanks for addressing my "consistency" nit picking, @samrichca.

Deferring to @joneubank for final approval

2023-12-01 21:28 UTC, joneubank requested changes
- Appreciate you putting so much detail into a docs file to help future devs.
- All the `trims` added to schemas is a good practice.

I feel like we can do better with creating the dictionaries for this form. I would like to see the use or Partial removed at the very least, and maybe a new function that returns an entire dictionary of a given language (rather than rebuilding it by requesting each property individually).

Other than that, I think it would be good to incorporate the type changes I recommended in the other PR.

2023-12-01 21:31 UTC, alyssadsouza commented on packages/types/src/entities/Name.ts
> +export const Name = z.string().trim().regex(name);
I was looking at the ticket you added where `Name` and `PhoneNumber` fail validation when the form returns no response as an empty string but 1) the regex doesn't accept an empty string, and 2) optional fields that don't have a value should be `undefined` according to how we treat them in all other schemas #285 

Maybe we could update the regex to allow an empty string, and add a `NameOptional` schema that does a `transform` on empty strings to convert them to `undefined`, like this:

```ts
const name = /^[A-Za-z\s]*$/ // using `*` instead of `+` so it allows 0 occurrences

export const NameOptional = z
	.string()
	.trim()
	.regex(name)
	.transform((x) => x || undefined);
```

Then for the original `Name` schema just add a `min(1)` constraint:
```ts
export const Name = z.string().trim().regex(name).min(1);
```

This could go in a separate PR for that ticket, just leaving it here in case you have any thoughts

2023-12-04 16:08 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/types.ts
> +>;
not finished adding everything to the page yet, but this will be updated by me shortly.

2023-12-04 16:09 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +	const [successMessageDemo, setSuccessMessageDemo] = useState('');
it can be removed, we can check the network tab to see if the request worked.

2023-12-04 20:59 UTC, samrichca commented on packages/types/src/entities/Name.ts
> +export const Name = z.string().trim().regex(name);
thanks alyssa! added to appropriate ticket.

2023-12-04 23:35 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +export default ClinicianInviteFormComponent;
moved my files to components/views & components/common and made an additional ticket

2023-12-05 21:14 UTC, samrichca commented on apps/consent-ui/src/app/[lang]/invite/index.tsx
> +	const labelsDict: Partial<FormLabelsDictionary> = {
I ran into issues implementing this feedback with the current `kebab-case` in translation dictionaries. I made a ticket for changing kebab to camel, and a follow-up ticket for this form https://github.com/OHCRN/platform/issues/300

2023-12-05 21:14 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +	labelsDict: Partial<FormLabelsDictionary>;
I ran into issues implementing this feedback with the current `kebab-case` in translation dictionaries. I made a ticket for changing kebab to camel, and a follow-up ticket for this form https://github.com/OHCRN/platform/issues/300

2023-12-06 13:44 UTC, anncatton commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +	labelsDict: Partial<FormLabelsDictionary>;
what was the issue you ran into? i'm confused how the key case would affect creating types

2023-12-06 14:44 UTC, samrichca commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +	labelsDict: Partial<FormLabelsDictionary>;
I wanted to deconstruct the translations 

`const { 'kebab-case' } = ...`

2023-12-06 17:56 UTC, justincorrigible commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +	labelsDict: Partial<FormLabelsDictionary>;
Right, I've been thinking about this one, and as a quick stopgap to unblock you without ballooning the scope, you could destructure the ones you can, and separately have things like:
`const camelCase = dictionary['kebab-case'];`

which you could then remove on a cleanup followup PR that also fixes the casing.

2023-12-06 21:36 UTC, anncatton commented on apps/consent-ui/src/app/[lang]/invite/index.tsx
> +	const labelsDict: Partial<FormLabelsDictionary> = {
A followup question to what Jon mentioned - just to make sure I understand the goal with the new ticket: it's to make dictionaries for *each* form as we build them, correct? i.e. a ClinicianInviteFormDict, a ConsentWizardStep2Dict, etc etc? That was my original intention with having dictionaries dedicated to particular components, as opposed to trying to over-generalize with a "FormDictionary" of sorts.

Because even here, the `labelsDict` works with `satisfies FormLabelsDictionary` without the use of `Partial`.

2023-12-06 21:36 UTC, anncatton commented on apps/consent-ui/src/components/views/invite/ClinicianInviteForm/index.tsx
> +const guardianInfoFields: Partial<keyof ClinicianInviteRequest>[] = [
Is it possible to reuse the key names from `InviteGuardianFields` here instead?

2023-12-06 21:41 UTC, mistryrn reviewed
Lots of good stuff in here, I really like how modular the form components are! Just a few comments/questions below.

I checked out the branch and built/ran it locally, then did a quick aXe DevTools scan – we might need to take a look at how that `react-select` library works, since it's currently giving us a Critical a11y issue related to input labels (screenshot provided on PR comment).

One of the translations isn't currently showing up for me (`textDict['clinician-information']`), and I wasn't sure about the use of `{ required: true }` in the `rules` prop for the `SelectFieldSet`'s `Controller`.

Other than that, the only major question I had was regarding other errors, for things other than just `required` – I don't see that handled in this PR, but not sure if that was part of the scope or if it has already been discussed.

2023-12-06 21:41 UTC, mistryrn commented on apps/consent-ui/src/components/common/forms/fieldsets/inputs/SelectInput.tsx
> +		<Select
Not sure if this is a limitation of the `react-select` library, but I can't seem to find where/how it applies `label`s to the select `input`s.

When running the [aXe DevTools](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) I get a Critical Issue relating to the select input created, stating the form element does not have a label:
![Screen Shot 2023-12-06 at 4 13 08 PM](https://github.com/OHCRN/platform/assets/3392776/5376c543-ef34-4c25-a526-38b5291a1c3f)

Can you look into this and see if there's some way to have it apply an `aria-label` of the `value`, or something like that (or a better solution than that :P)

2023-12-06 21:49 UTC, anncatton commented on apps/consent-ui/src/components/ClinicianInviteForm/index.tsx
> +	labelsDict: Partial<FormLabelsDictionary>;
seems like in that case it would be better - if possible - to add this deconstruction in after the case change pr is in...i think you already have that work on the go?

2023-12-08 14:59 UTC, samrichca commented on apps/consent-ui/src/components/common/forms/fieldsets/inputs/SelectInput.tsx
> +		<Select
I had to change instanceId to inputId, my b.

2023-12-08 15:05 UTC, samrichca commented on apps/consent-ui/src/components/views/invite/ClinicianInviteForm/index.tsx
> +const guardianInfoFields: Partial<keyof ClinicianInviteRequest>[] = [
I can't reply directly to your other comment

I'd like to have dictionaries for each form/component but I was thinking we could reuse some of the form labels and have one source of truth for translating them, e.g. we can get "first name/prénom" from a shared dictionary. is that alright or should they be completely separate?

2023-12-08 18:08 UTC, samrichca commented on apps/consent-ui/src/app/[lang]/invite/index.tsx
> +	const labelsDict: Partial<FormLabelsDictionary> = {
yes, I want to have separate dictionaries for all the forms for type safety, but I'm hoping they can share some of the translations from `FormLabelsDictionary`

2023-12-13 14:25 UTC, anncatton reviewed
Thanks for all the comments/TODO ticket links @samrichca ! I just added one comment to add one more TODO ticket link, and a minor type change.

I'd like @mistryrn and @justincorrigible to leave a final approval for any changes they requested; i think the latest changes + the followup tickets address the rest of @joneubank 's feedback but i'd like their 👀 there too for a sanity check.

Can we link the followup tickets to the original #186 too?

2023-12-13 14:25 UTC, anncatton commented on apps/consent-ui/src/components/views/Invite/ClinicianInviteForm/index.tsx
> +			guardianInfoFields.forEach((field: Partial<keyof ClinicianInviteRequest>) => {
i think the type on `field` can be removed since `guardianInfoFields` is already typed above

2023-12-13 15:57 UTC, samrichca commented on apps/consent-ui/src/components/common/Form/types.ts
> +	error?: any; // TODO harmonize error dictionary & RHF errors
added

2023-12-13 16:03 UTC, samrichca commented
added follow up tickets to this ticket

2023-12-13 18:27 UTC, mistryrn reviewed
All the recent changes look good! Thanks for highlighting the follow-up tickets where applicable 🙏 

My only outstanding question/comment (apologies if this has already been covered earlier in the PR process) is regarding the optional "Preferred Name" field: have we figured out how to make it actually optional on the form? I'm still getting a "required" message when I try to submit the form without filling out that field:
![Screen Shot 2023-12-13 at 1 23 00 PM](https://github.com/OHCRN/platform/assets/3392776/917a4211-802d-41a2-a166-aad34a028d43)

2023-12-13 18:39 UTC, samrichca commented
@mistryrn very good question, there's another followup ticket for that. https://github.com/OHCRN/platform/issues/285

2023-12-13 22:19 UTC, mistryrn approved these changes
Thanks for clarifying/listing out all the follow-up tickets, @samrichca !

Since the follow-up/out-of-scope work is captured in the tickets you listed in this comment (https://github.com/OHCRN/platform/issues/186#issuecomment-1854194859), I'm good to proceed with merging this PR.

Do we have a plan/order/priority for those follow-up tasks?

I think we'll still need @joneubank to give final approval since his prior change request will block you from merging though.

2023-12-13 22:49 UTC, samrichca commented
thanks @mistryrn, I've updated that comment with details about priority and status.

if @joneubank isn't available tomorrow morning I'll see if @justincorrigible can merge it

2023-12-14 02:42 UTC, anncatton approved these changes

2023-12-14 14:47 UTC, merged