✨ POC: Build `POST /invites` route in Consent API (#168)
OHCRN/platform pull request #279
Opened 2023-11-22 21:50 UTC by alyssadsouza

## Description of Changes

Implemented the "happy path" `POST /invites` route in Consent API which integrates with Data Mapper and Consent DAS + PI DAS to create a clinician invite. Also added a POC for unit testing on the `services`.

### Consent API
Added the `POST /invites` route with incomplete error handling (E2E error handling to be considered in #275).
- Renamed the `participantResponses.ts` service file to `create.ts` and added the `createInvite` service which makes a POST request to Data Mapper's `POST /invites` route
- Created base `axiosClient` instance to reuse for API calls in Consent API
- Added a test suite for the `createInvite` service in `tests/services/create.ts` as a POC
- Added package [`url-join`](https://www.npmjs.com/package/url-join) to format API request path names

### Types
- Added type `ResponseValidationErrorResponse` to support (tentative) error handling required by `POST /invites` route

### Special Instructions
Before running these changes, you will need to install `url-join`:
```
pnpm i
```

## PR Readiness Checklist

- [x] "Expected Outcome(s)" in ticket have been met
- [x] Ticket number included in PR title
- [x] Connected ticket to PR
- [x] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [x] Manual testing completed
- [x] Builds locally without errors or warnings
- [x] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [x] Added copyrights to new files

2023-11-22 21:57 UTC, alyssadsouza commented on apps/consent-api/tests/services/create.spec.ts
> +			expect(response.inviteSentDate).toBeDefined();
This test case is pretty trivial even if it's just meant to be the groundwork for unit testing... although what it does do that the Zod schemas can't do is verify that the response body matches all the fields that were present in the request body exactly (even though that is a very obvious expected behaviour)

2023-11-22 21:58 UTC, alyssadsouza commented on apps/consent-api/src/service/axiosClient.ts
The `service` dir will need to be renamed to `services`, I'm guessing in a new PR

2023-11-23 15:51 UTC, joneubank commented on apps/consent-api/src/middleware/recaptcha.ts
> +import { ErrorResponse } from 'types/httpErrors';
This is evidence I broke the linting rules. I will retire in shame.

2023-11-23 22:02 UTC, alyssadsouza commented on apps/consent-api/tests/services/create.spec.ts
> +			recaptchaToken: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe', // test recaptchaToken key
the tests are failing because this token isn't valid when tests are run in the root dir, though it passes when running tests in `consent-api`

2023-11-24 14:11 UTC, alyssadsouza commented on apps/consent-api/tests/routers/invites.ts
> +			recaptchaToken: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe', // test recaptchaToken key
the tests are failing because this token isn't valid when tests are run in the root dir, though it passes when running tests in consent-api

2023-11-24 14:28 UTC, alyssadsouza commented on apps/consent-api/tests/routers/invites.spec.ts
> +			recaptchaToken: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe', // test recaptchaToken key
the tests are failing because this token isn't valid when tests are run in the root dir, though it passes when running tests in consent-api

2023-11-24 16:20 UTC, alyssadsouza commented on apps/consent-api/tests/routers/invites.spec.ts
> +			recaptchaToken: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe', // test recaptchaToken key
using [`stubEnv`](https://vitest.dev/api/vi#vi-stubenv) to set `NODE_ENV=development` for now to pass tests (setting the `RECAPTCHA_SECRET_KEY` isn't working for some reason), will remove later when the env vars setup for Jenkins is figured out

2023-11-24 16:48 UTC, joneubank requested changes
Requesting changes to the error handling written around the axios request to datamapper.

2023-11-24 16:48 UTC, joneubank commented on apps/consent-api/src/services/create.ts
> +}: ClinicianInviteRequest): Promise<
Why are we deconstructing all this instead of just passing the entire object?

2023-11-24 16:48 UTC, joneubank commented on apps/consent-api/src/services/create.ts
> +};
Should not be returning `any`, if you are defining a stub with a TODO let's at least specify the inputs/outputs accurately.

2023-11-24 16:48 UTC, joneubank commented on apps/consent-api/src/services/create.ts
> +	return ClinicianInviteResponse.safeParse(data);
We also need to handle failed requests. Should have a try catch around axios requests to handle unexpected thrown errors, and also have a check for non 200 response codes (axios responses have a `.ok`).

It is good that we are checking for invalid response structures and I really like that we are returning a type that includes a success/failure boolean, but I don't think we need to return the validation info (we just log it so that a developer can fix the problem). When another system is returning invalid responses our service should return an error 500 with a generic "Unexpected server error" message.

There is a really good pattern for functions like this, where on success you return an object of type `{success:true, data: ClinicianInviteResponse}` and on failure you can return `{success:false, message: string}`. We could create a generic type for this response so we don't need to return the Zod parse error, here's a gist I have of a `Result<T>` type that accomplishes this: https://gist.github.com/joneubank/ac5a5b30dafb84915d633131c54aa028

2023-11-24 16:48 UTC, joneubank commented on apps/consent-api/src/routers/invites.ts
> +			}
Repeating my previous comment... We don't need to tell the client about failures from our backend systems. We should just return a generic server error message and log the problem for us to resolve.

2023-11-24 16:48 UTC, joneubank commented on apps/consent-api/tests/routers/invites.spec.ts
> +vi.stubEnv('NODE_ENV', 'development');
Perhaps we can have a common file to setup all tests, I imagine there are other tests that will need this.

2023-11-24 16:48 UTC, joneubank commented on apps/consent-api/tests/routers/invites.spec.ts
> +		vi.restoreAllMocks();
👍

2023-11-24 16:48 UTC, joneubank commented on apps/consent-api/tests/routers/invites.spec.ts
> +		vi.unstubAllEnvs();
Is this required after each test? Or just unstub at the end? I don't know what vitest recommends.

2023-11-24 16:48 UTC, joneubank commented on docs/shared-types.md
> +>**Note**: Zod's `parse` does **not** throw an error if it encounters unrecognized fields, it simply parses those out of the output. To disallow unknown fields, see [`strict()`](https://zod.dev/?id=s
Thanks for including a reference link with this note :)

2023-11-24 16:48 UTC, joneubank commented on packages/types/src/httpErrors/RequestValidationErrorResponse.ts
> +	details: ZodIssue[];
🙏

2023-11-24 16:52 UTC, alyssadsouza commented on apps/consent-api/src/services/create.ts
> +}: ClinicianInviteRequest): Promise<
Ah good point, no reason I'll change that

2023-11-24 16:58 UTC, alyssadsouza commented on apps/consent-api/src/services/create.ts
> +};
This was just code I moved over from `services/participantResponses.ts` to `services/create.ts` - not sure if I should delete it since it's an old implementation and needs to be updated anyway (which it will when the consent question responses endpoint is built)

2023-11-24 21:02 UTC, alyssadsouza commented on apps/consent-api/src/services/create.ts
> +	return ClinicianInviteResponse.safeParse(data);
Thanks for the gist! I don't see an `ok` field, there is a `statusText` field https://axios-http.com/docs/res_schema which returns the HTTP message for the status code (e.g. `200: "OK"`, `201: "Created"`) so in this case we'd be looking for `statusText === "Created"`. Maybe it's better to just validate the status code is a 201 as we explicitly set in the `data-mapper` endpoint?

The other thing I'm wondering about the `Result` type is if it includes all the information we want. The bad request example I run into a lot is where the participant email I'm creating an invite with is not unique (which is a constraint on it in the `PI` database), so there already exists an invite with that same email address, and that cannot be validated (at least not yet) until we try to create an invite in PI DAS and get a Prisma error. I think that would classify as a 400 error, so I'm wondering what's the best way to return that information from `createInvite` to the router so that it gives the correct error.

2023-11-24 21:13 UTC, alyssadsouza commented on apps/consent-api/src/services/create.ts
> +			return failure(error.message);
Not sure how this should be treating errors that might be more than server errors, for example: "an invite with that participant email already exists", because I think ideally we would want to return a 400 response in the router.

2023-11-24 21:17 UTC, alyssadsouza commented on apps/consent-api/tests/routers/invites.spec.ts
> +		vi.unstubAllEnvs();
From the docs https://vitest.dev/api/vi.html#vi-unstuballenvs:

> Restores all import.meta.env and process.env values that were changed with vi.stubEnv. When it's called for the first time, Vitest remembers the original value and will store it, until unstubAllEnvs is called again.

I _think_ that means each use will just restore the previous value? In which case we would only want to call it at the end.

2023-11-25 18:59 UTC, joneubank reviewed
Responded to your question re: existing invite. Good question.

Also something about logger formatting.

2023-11-25 18:59 UTC, joneubank commented on apps/consent-api/src/services/create.ts
> +		}
I don't think 201 is necessarily an error condition - so long as we have received the data we need in the body we can validate it. We can accept this response and pass teh data to our validator below... if it is an empty body or fails validation then we handle it there.

2023-11-25 18:59 UTC, joneubank commented on apps/consent-api/src/services/create.ts
> +			logger.error(`[Data-Mapper] 😱 'POST /invites' had an invalid response`, invite.error.issues);
emoji is cute and made me laugh... I'm going to ask for us to keep log messages simple and dry though, sorry :( Can we remove the emoji?

I would like to recommend another approach than this `[Data-Mapper]` tag here. As is, it could be interpreted as the error being thrown within the data-mapper application. What we would like to express is that this log message comes from the dataMapperClient. I added a mechanism to do this to the logger:

```ts
import serviceLogger from '../logger.js';
const logger = serviceLogger.forModule('DataMapperClient');
// ...
logger.error('POST /invites', 'Received invalid data in response.', invite.error.issues);
// "[Consent-API.DataMapperClient] POST /invites - Received invalid data in response. - { ... issues ... }
```

2023-11-25 18:59 UTC, joneubank commented on apps/consent-api/src/services/create.ts
> +			return failure(error.message);
Yes, interesting use case. Since we have multiple response statuses now, not just Success and Failure, we can create a more descriptive type to respond with that has multiple statuses:

```ts
type CreateInviteResult =
	| { status: 'SUCCESS'; data: CreateInviteResponse }
	| { status: 'SYSTEM_ERROR'; message: string }
	| { status: 'INVITE_EXISTS'; message: string };

export const createInvite = async (
	inviteRequest: ClinicianInviteRequest,
): Promise<CreateInviteResult> =>
```

So now when we get the result back we can handle these cases in a switch:

```ts
const inviteResult = await createInvite(req.body.data);
switch(inviteResult.status) {
  case 'SUCCESS': {
    // validate inviteResult.data
    return res....;
  }
  case 'SYSTEM_ERROR': {
    return res.status(500).json(ErrorResponse(inviteResult.message);
  }
  case 'INVITE_EXISTS': {
    return res.status(400).json(ErrorResponse(inviteResult.message);
  }
```

The advantage of structuring our code this way is that our `createInvite` code now details all the different cases that our service may need to deal with. All our code downstream doesn't know about the HTTP communication and how that API works, it only knows if the invite was created, and if not created it has a list of reasons why.

Its worth noting: I don't know if there is an error sending a duplicate invitation... double check with Rakesh and Brandon how the UX is supposed to work in that case.

2023-11-25 18:59 UTC, joneubank commented on apps/consent-api/tests/routers/invites.spec.ts
> +		vi.unstubAllEnvs();
sounds useful for afterAll. Thanks for the reference!

2023-11-27 17:59 UTC, alyssadsouza commented on apps/consent-api/src/services/create.ts
> +			return failure(error.message);
Still waiting on word about that from Brandon, but I updated the `Result` type to use `status` to indicate success or failure as opposed to the `success` boolean, since it allows us to structure our error handling like what you suggested. If it's overcomplicating things right now then I'm open to removing that type from the shared `types` package altogether and just going with the local `CreateInviteResult` type you defined above, but I think it's useful to have the global `Result` type with the `success()`, `failure()` and `alternate()` methods you defined in the gist so we can use them in other routers and have consistency in the services response types.

2023-11-27 21:30 UTC, alyssadsouza commented on apps/consent-api/src/services/create.ts
> +			// TODO: E2E error handling → this could be any error from requests to data-mapper, pi-das or consent-das
Yeah that's right, `error.response.data` returns whatever our error response was.

2023-11-28 15:57 UTC, anncatton commented on apps/consent-api/src/middleware/recaptcha.ts
>  		// TODO: Need a formatted error for reCAPTCHA validation failures
does this `TODO` apply now that the error is in place? or is it referring to something else 🤔

2023-11-28 15:57 UTC, anncatton commented on apps/consent-api/src/middleware/recaptcha.ts
>  		next();
can add `return`s here, like:
``` if (recaptchaVerified) {
		return next();
}
return res.status(400).json(ErrorResponse(RECAPTCHA_ERROR, 'Valid reCAPTCHA token is required.'));
```
can get rid of the `else` too

2023-11-28 15:57 UTC, anncatton commented on apps/consent-api/src/middleware/recaptcha.ts
>  const verifyRecaptcha = async (recaptchaToken?: string | null) => {
while in this file can you update the `console.log()`s to `logger` statements?

2023-11-28 15:57 UTC, anncatton commented on packages/types/src/httpErrors/ErrorResponse.ts
> +	error: ErrorName | 'NOT_IMPLEMENTED'; // TODO: remove once all routes are implemented
👍

2023-11-28 15:57 UTC, anncatton commented on packages/types/src/httpErrors/ConflictErrorResponse.ts
> +	target,
curious about `target` as a key name...i think makes more sense to call it `fields` or `onFields`...what do you think?

2023-11-28 15:57 UTC, anncatton commented on packages/types/src/httpErrors/ConflictErrorResponse.ts
> + * Creates a ConflictErrorResponse containing the target fields causing the conflict and a message detailing it.
thanks for the documentation!

2023-11-28 15:57 UTC, anncatton commented on apps/consent-api/tests/routers/invites.spec.ts
> +		vi.unstubAllEnvs();
For the env config, should we just stub the entire app config instead? so no surprises

2023-11-28 15:57 UTC, anncatton commented on apps/consent-api/src/services/create.ts
> +};
Can we leave it as is for now? Since it's not fully implemented but this request is referenced elsewhere iirc, but isn't part of the work for this PR.

2023-11-28 15:57 UTC, anncatton commented on packages/types/src/httpErrors/Result.ts
> +	target?: string[]; // list of target fields pertaining to the error, for example `emailAddress` for a conflict error
instead of adding the `target` key to the `Failure` type, i wonder if we can extend this type when this is applicable, so that `Failure` remains more basic in structure. 🤔

2023-11-28 16:20 UTC, mistryrn reviewed
Awesome work! Just a few small requests 🙂

2023-11-28 16:20 UTC, mistryrn commented on packages/types/src/httpErrors/Result.ts
> +export const success = <T>(data: T): Success<T> => ({ status: 'SUCCESS', data });
Bit of a nitpick, but if we're going to include `success`, should we rename this from `httpErrors` to `httpResponses`?

2023-11-28 16:20 UTC, mistryrn commented on packages/types/src/httpErrors/ErrorResponse.ts
> +	error: ErrorName | 'NOT_IMPLEMENTED'; // TODO: remove once all routes are implemented
👍

2023-11-28 16:33 UTC, alyssadsouza commented on packages/types/src/httpErrors/ConflictErrorResponse.ts
> +	target,
Yeah, I got `target` from the name that `PrismaClientKnownRequestError` gives to the field that caused the error https://www.prisma.io/docs/reference/api-reference/error-reference#prismaclientknownrequesterror, but since this is specific to a conflict error something like `onFields` is probably more clear.

2023-11-28 16:37 UTC, alyssadsouza commented on packages/types/src/httpErrors/Result.ts
> +export const success = <T>(data: T): Success<T> => ({ status: 'SUCCESS', data });
I was thinking that too, I'll do that

2023-11-28 20:09 UTC, alyssadsouza commented on packages/types/src/httpErrors/Result.ts
> +	target?: string[]; // list of target fields pertaining to the error, for example `emailAddress` for a conflict error
good idea! added a `Conflict` type to `Results.ts` with the assumption we will use it more than once

2023-11-28 20:09 UTC, alyssadsouza commented on packages/types/src/httpErrors/ConflictErrorResponse.ts
> +	target,
renamed to `onFields`

2023-11-28 21:38 UTC, mistryrn reviewed
New changes look great, thanks for getting those updates in so quickly! I think Ann had one or two outstanding bits of feedback that she's thinking through, so I'll wait for that before approving, but other than that I think this is good to go 😄

2023-11-29 15:21 UTC, anncatton commented on packages/types/src/httpResponses/Result.ts
> +export const conflict = <ConflictStatus>(
from zoom call: we can remove this extended type and use `failure` with `INVITE_EXISTS` with specifics on the conflict coming from the message

2023-11-29 15:21 UTC, anncatton commented on packages/types/src/httpResponses/ConflictErrorResponse.ts
> +export const ConflictErrorResponse = (
i'm still happy to keep this extended type, it's a nice convenience and is extra readable. but we can remove the `onFields` property and rely on the information in the message.

2023-11-29 16:22 UTC, alyssadsouza commented on apps/consent-api/src/routers/invites.ts
> +		} catch (error) {
Actually no, because if none of the cases are caught the code will just resume after the `switch` statement, i.e. end there. It wouldn't be caught in the `catch` block because no error would be thrown, the `try` block just completes and the function returns nothing. We don't necessarily *need* an explicit default case if we add a final return statement at the end of the `switch` statement, which will just run if none of the other cases are caught, so basically acting as a default. I'll just add that it in and have it return a 500 response with an "unexpected error" message.

2023-11-29 16:30 UTC, alyssadsouza commented on apps/consent-api/src/routers/invites.ts
> +		} catch (error) {
Update: TS catches any code under that `switch` as unreachable code because it can tell that all the status cases were caught 😛
<img width="772" alt="Screenshot 2023-11-29 at 11 28 44 AM" src="https://github.com/OHCRN/platform/assets/70766739/adb8b70b-bac4-47ad-87af-5e3dd0f94ed3">
And nice to see it works if I remove a case:
<img width="804" alt="Screenshot 2023-11-29 at 11 29 01 AM" src="https://github.com/OHCRN/platform/assets/70766739/d33c4edc-6227-4cb9-8a36-b5bd3965e99b">
So... I'll just leave it as is.

2023-11-29 16:51 UTC, anncatton commented on apps/consent-api/src/routers/invites.ts
> +		} catch (error) {
Nice! Thanks for verifying this 😀

2023-11-29 20:03 UTC, anncatton commented on docs/error-handling.md
> +| `RECAPTCHA_ERROR`          | 400    | A ReCAPTCHA token could not be verified.
thanks for this! 😎

2023-11-29 20:30 UTC, mistryrn approved these changes
Great work on this 👏 Looks like all of mine and @anncatton 's feedback has been addressed so I'm approving, but I think we still need approval from @joneubank before you can merge since he requested changes previously

2023-11-29 20:30 UTC, mistryrn commented on docs/error-handling.md
This is fantastic 👏

2023-12-01 22:50 UTC, joneubank requested changes
There is so much good stuff in here, thanks a million. If it seems like I'm being picky or refactoring too much it is because the PR is good and that makes it engaging, also since this is going to be a template for future work I do want to push our standards a bit.

Couple suggestions for rework here, honestly not much left to cleanup.

I love all the documentation added. Thats huge.

2023-12-01 22:50 UTC, joneubank commented on apps/consent-api/src/services/create.ts
> +}): Promise<any> => {
No `any` responses! If you know the type you want to return, then use that so TS can validate you are returning the correct type. Otherwise, don't declare return type and let TS determine what type the function returns.

This function looks to be a placeholder for future dev, but let's not put the wrong types in it (in fear that they get used in the future).

2023-12-01 22:50 UTC, joneubank commented on packages/types/src/httpResponses/Result.ts
> +// Success and Failure types
File needs copyright header.

2023-12-01 22:50 UTC, joneubank commented on packages/types/src/httpResponses/Result.ts
> +export type Either<A, B> = Success<A> | Failure<B>;
With how you have refactored the Result to have a FailureStatus generic, we no longer need `Either`. Can remove this.

2023-12-01 22:50 UTC, joneubank commented on packages/types/src/httpResponses/Result.ts
> +});
Can remove this now that `failure` takes a generic

2023-12-01 22:50 UTC, joneubank commented on packages/types/src/httpResponses/Result.ts
> +};
I like how this has been extended to include multiple failure statuses. I would clean it up a bit by reworking it as:
```ts
// Success and Failure types
export type Success<T> = { status: 'SUCCESS'; data: T };
export type Failure<FailureStatus extends string, T = void> = {
	status: FailureStatus;
	message: string;
	data: T;
};

/**
 * Represents a response that on success will include data of type T,
 * otherwise a message will be returned in place of the data explaining the failure.
 * The failure object has data type of void.
 */
export type Result<T, FailureStatus extends string, FailureData = void> =
	| Success<T>
	| Failure<FailureStatus>;
```

This way we don't need the `Either` type, as we can include that in the HttpFailure. That also means we can remove the `alternate` method. These were awkwardly named anyways.

Using the `extends string` with the FailureStatus generic means that the implementer must state which failure cases could be returned. It could look like:

```ts
type DoActionResult = Result<{data: string}, 'INVITE_EXISTS' | 'SYSTEM_ERROR'>;
```

If you also want data to be returned with the error:

```ts
type DoActionResult = Result<{data: string}, 'INVITE_EXISTS' | 'SYSTEM_ERROR', {failureData: number}>;
```

2023-12-01 22:50 UTC, joneubank commented on packages/types/src/httpResponses/Result.ts
> +});
Will need a generic for the return data type.

2023-12-01 22:50 UTC, joneubank commented on apps/consent-api/tests/config.ts
> +};
This is a really good idea, but I might suggest doing this a bit differently... We realyl want to make sure our `getAppConfig` function from the config module is returning a fully configured `AppConfig` object, and we may want to allow individual test suites to modify the env returned.  Here is an alternative approach I would recommend:

```ts
import * as config from '../src/config.js';
import { AppConfig } from '../src/config.js';

export const mockEnv = (values?: Partial<AppConfig>) => {
	// Need to set the NODE_ENV since there are currently places in teh code checking the process.env.NODE_ENV directly instead of relying on our config.
	vi.stubEnv('NODE_ENV', values?.isProduction ? 'production' : 'development');

	const defaultConfig: AppConfig = {
		dataMapperUrl: 'http://localhost:8081',
		express: {
			port: '8080',
		},
		isProduction: false,
		recaptcha: {
			secretKey: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe',
		},
	};

	vi.spyOn(config, 'getAppConfig').mockReturnValue({ ...defaultConfig, ...values });
};
```

This will ensure that we always have the full `AppConfig` in the mock, since TS will yell at us if we are missing any default properties. We can also now provide replacement values for any test suite.

One added benefit, it will catch code that is reading directly from the `process.env` in stead of relying on our config module (since we aren't adding mock env values, other than `NODE_ENV` which is a standard).

2023-12-01 22:50 UTC, joneubank commented on apps/consent-api/tests/routers/invites.spec.ts
> +			data: mocks.inviteRequest,
👍

2023-12-01 22:50 UTC, joneubank commented on apps/consent-api/src/services/create.ts
> +			}
👍

2023-12-01 22:50 UTC, joneubank commented on apps/consent-api/src/routers/invites.ts
> +			}
❤️

2023-12-01 22:50 UTC, joneubank commented on apps/consent-api/src/routers/invites.ts
> +					return res.status(201).send(invite.data);
Could this also use `.json`?

2023-12-01 22:50 UTC, joneubank commented on apps/consent-api/src/middleware/recaptcha.ts
> +		logger.debug('Successful ReCAPTCHA verification');
This is going to get real noisy without giving us much useful info to work with, but we can keep it until we get annoyed.

2023-12-01 22:50 UTC, joneubank commented on apps/consent-api/src/middleware/recaptcha.ts
> +const logger = serviceLogger.forModule('ReCAPTCHAVerification');
🙏

2023-12-01 23:16 UTC, alyssadsouza commented on packages/types/src/httpResponses/Result.ts
> +export type Either<A, B> = Success<A> | Failure<B>;
Ah that's right! Thanks for catching that

2023-12-04 16:14 UTC, alyssadsouza commented on packages/types/src/httpResponses/Result.ts
> +};
It looks like the `alternate` type is needed because TS has a fit if you try to make generic typed function params optional so I'm leaving it in because I think it's more convenient than having to explicitly pass `undefined` to `failure` when I don't want to give it data

2023-12-04 18:02 UTC, joneubank approved these changes

2023-12-04 18:50 UTC, merged