💄 #233: Style invite form
OHCRN/platform pull request #323
Opened 2023-12-18 16:04 UTC by samrichca

## Description of Changes

### Consent-UI

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2023-12-18 16:18 UTC, samrichca commented on apps/consent-ui/src/components/common/Button/index.tsx
> +	onClick?: (e: React.SyntheticEvent<HTMLElement>) => any;
submit buttons in our forms can't have onClick events & must have `type="submit"`

2024-01-04 16:00 UTC, samrichca commented on apps/consent-ui/src/components/layouts/SideImageLayout/SideImageLayout.module.scss
> +	@media (min-width: theme('screens.md')) {
original media queries for this component created an issue where there was no navigation at all at exactly 1024px screen width

2024-01-04 16:01 UTC, samrichca commented on apps/consent-ui/src/components/views/Invite/ClinicianInviteForm/index.tsx
> +			console.log('form data', data);
this console log is part of the ticket requirements because the API call doesn't work yet

2024-01-05 05:57 UTC, ciaranschutte reviewed
Copyrights can be 2024 now instead of 2023

2024-01-05 16:46 UTC, samrichca commented on apps/consent-ui/src/components/views/Invite/ClinicianInviteForm/index.tsx
> +Object.assign(styles, layoutStyles);
nah, this is the documented way to use multiple CSS modules: https://github.com/css-modules/css-modules/blob/master/docs/import-multiple-css-modules.md

2024-01-05 17:44 UTC, justincorrigible commented on apps/consent-ui/src/components/views/Invite/ClinicianInviteForm/index.tsx
> +Object.assign(styles, layoutStyles);
does this mutation possibly affect the imported `styles` in other contexts?

even though documentation may use that pattern, I'm inclined to suggest we'd stick to immutable patterns for the sake of consistency... but I'm not certain whether that's just my Functional Programming stickler side speaking.

```suggestion
const inviteFormStylesOrWhatever = Object.assign({}, styles, layoutStyles);
```

2024-01-08 16:35 UTC, mistryrn commented on apps/consent-ui/src/components/common/Form/FormSection/FormSection.module.scss
> +	width: calc(100% + 2rem);
Just out of curiosity, is there a reason for adding the extra width and negative margin here? Versus just specifying the top and bottom padding only:
```css
padding: 1rem 0;
```

I may have missed something in the designs, or maybe there's a specific responsive layout where the negative margin is necessary here so please let me know

2024-01-08 17:14 UTC, samrichca commented on apps/consent-ui/src/components/common/Form/FormSection/FormSection.module.scss
> +	width: calc(100% + 2rem);
it's to line up the grey sections with the rest of the page 
<img width="743" alt="image" src="https://github.com/OHCRN/platform/assets/3540896/8faa16dd-ec93-4b52-b19b-add0123d13cb">

2024-01-08 17:15 UTC, samrichca commented on apps/consent-ui/src/components/views/Invite/ClinicianInviteForm/index.tsx
> +Object.assign(styles, layoutStyles);
`Object.assign(styles, layoutStyles)` mutates the imported styles object in this file and doesn't affect global scope

updated the code to remove the mutation

2024-01-08 17:25 UTC, mistryrn commented on apps/consent-ui/src/components/common/Form/FormSection/FormSection.module.scss
> +	width: calc(100% + 2rem);
Ah, that makes sense. Thanks!

2024-01-09 02:45 UTC, mistryrn requested changes
Really great work! 😃 Found a few small things during my testing, as noted in the comments below, but the UI is really starting to come together! Looks great!!

Aside from the comments below, I do think we should rename `Callout` to `Tooltip` (and the related functions, styles, and translations). Sorry, I know it's a pain! 😬 But I think this component better matches the definition of a Tooltip than a Callout: https://medium.com/@adamshriki/choosing-the-right-ui-component-for-communication-with-your-users-523499c39490

2024-01-09 02:45 UTC, mistryrn commented on apps/consent-ui/src/components/common/Form/fieldsets/SelectFieldSet/index.tsx
> +			className={clsx(styles.selectFieldSet, className)}
Looks like we're not passing the `error` prop down here, so validation errors never render.

```suggestion
			className={clsx(styles.selectFieldSet, className)}
			error={error}
```

2024-01-09 02:45 UTC, mistryrn commented on apps/consent-ui/src/components/common/Form/fieldsets/TextFieldSet/index.tsx
> +			className={className}
Same as the `SelectFieldSet`, looks like we're not passing the `error` prop down into the `FieldSet` here:
```suggestion
			className={className}
			error={error}
```

2024-01-09 02:45 UTC, mistryrn commented on apps/consent-ui/src/components/common/Modal/index.tsx
> -					<div ref={ref}>
Looks like removing this extra div and moving the ref onto the wrapper breaks the functionality of the `useDetectClickOutside` library that Alyssa added.

I don't know why, but I've seen it with other 3rd party libraries for this kind of thing before (I think there was something in the old platform-ui that behaved similary – I removed what I thought was a redundant/pointless div and all of a sudden the functionality was borked 😅)

If we restore that extra div and move the ref back onto it instead of the wrapper, clicking outside closes the modal again. But if you can figure out why/find a better solution that would be acceptable too!

2024-01-09 02:45 UTC, mistryrn commented on docs/forms.md
Thanks for updating these docs!

2024-01-10 16:50 UTC, mistryrn reviewed
Thanks for getting those changes in! Just one a11y regression to address in the `SelectInput`, and a few minor case changes needed after the renaming from callout to tooltip 🙂

2024-01-10 16:50 UTC, mistryrn commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +					inputId={`input-${id}`}
It looks like now that we're using an id generated from `useId` here instead of the `id` prop passed in from `SelectFieldSet` (https://github.com/OHCRN/platform/blob/4fc1799f304fa4d2dafc92591f5b49a7f9198517/apps/consent-ui/src/components/common/Form/fieldsets/SelectFieldSet/index.tsx#L77), the `for` prop on the label that the `FieldSet` creates no longer points at the generated select input.

![Screenshot 2024-01-10 at 11 28 44 AM](https://github.com/OHCRN/platform/assets/3392776/bd82065e-69f9-42bd-9e9d-ee6899993bab)

We're getting the same a11y error we were getting before (https://github.com/OHCRN/platform/pull/235#discussion_r1417987720) on the select inputs, `Form elements must have labels`.

![Screenshot 2024-01-10 at 11 31 29 AM](https://github.com/OHCRN/platform/assets/3392776/25641489-f5bb-449c-9564-9d358b35e762)

2024-01-10 17:24 UTC, samrichca commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +					inputId={`input-${id}`}
good catch, updated

2024-01-10 17:24 UTC, samrichca commented on apps/consent-ui/src/components/common/Form/fieldsets/Tooltip/useTooltip.tsx
> +	const [tooltipVisible, settooltipVisible] = useState<boolean>(false);
thanks, fixed

2024-01-10 17:49 UTC, anncatton commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +					onChange={(val: SelectOnChangeArg<V>) => {
i think the typing on the `val` arg here is unnecessary, looks like it already shows as `SingleValue<string | FormSelectOption<V>>` in Intellisense

2024-01-10 17:49 UTC, anncatton commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +						if (typeof val === 'string') {
with the type of `val` being `SingleValue<string | FormSelectOption<V>>`, i'm not sure this `if` clause would ever be true? i'm assuming the empty string case is for when and option hasn't yet been selected (?)

2024-01-10 17:49 UTC, anncatton commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +type SelectOnChangeArg<V extends string> = SingleValue<string | FormSelectOption<V>>;
may not need this type, see comment below

2024-01-10 18:11 UTC, samrichca commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +						if (typeof val === 'string') {
correct about the empty string case, I added a comment to clarify this

2024-01-10 20:36 UTC, anncatton commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +						if (typeof val === 'string') {
is the `typeof val === 'string'` relevant here tho? it looks like the return should either be `onChange(val.value)` or `onChange('')`. Or perhaps i'm missing something..?

2024-01-10 20:51 UTC, samrichca commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +						if (typeof val === 'string') {
if I don't handle the string case explicitly, I get a TS issue

```ts
let onChangeParam = val;
						if (val?.value !== undefined) {
							onChangeParam = val.value;
						}
```

`Property 'value' does not exist on type 'string | FormSelectOption<V>'. Did you mean 'valueOf'?
  Property 'value' does not exist on type 'string'.`

2024-01-11 00:16 UTC, anncatton commented on apps/consent-ui/src/components/common/Form/fieldsets/inputs/SelectInput.tsx
> +						if (typeof val === 'string') {
hmm yeah i just tried locally and see what you mean...i guess there is something in that `SingleValue` type i'm not getting. 🤷‍♀️

2024-01-11 00:17 UTC, anncatton reviewed
lgtm, but i'll let @mistryrn do final approval

2024-01-11 01:19 UTC, mistryrn approved these changes
Looks good! 🚀

2024-01-12 15:52 UTC, merged