POC: environment variables
OHCRN/platform pull request #48
Opened 2023-08-22 20:50 UTC by samrichca

2023-08-22 20:55 UTC, samrichca commented on apps/consent-ui/src/app/[lang]/participant/consent-forms/ConsentButton.tsx
> +	const appConfig = useAppConfigContext();
getting an environment variable in a client component

2023-08-22 20:55 UTC, samrichca commented on .vscode/extensions.json
> +		"bradlc.vscode-tailwindcss"
this tailwind plugin is nice (rakesh approved)

2023-09-08 08:39 UTC, ciaranschutte requested changes

2023-09-08 08:39 UTC, ciaranschutte commented on apps/consent-ui/src/components/AppConfig/index.tsx
> +const DefaultAppConfigContext = createContext(defaultContextValues as AppConfig);
no need to create 2 seperate contexts - just give the one context different values

2023-09-11 17:47 UTC, samrichca commented on apps/consent-ui/src/components/AppConfig/index.tsx
> +const DefaultAppConfigContext = createContext(defaultContextValues as AppConfig);
i'm not sure what to do with line 48-52 in that case

2023-09-12 14:04 UTC, ciaranschutte requested changes

2023-09-12 14:04 UTC, ciaranschutte commented on apps/consent-ui/src/components/AppConfig/index.tsx
> +const DefaultAppConfigContext = createContext(defaultContextValues as AppConfig);
Best to set the value of context that you created, instead of creating new contexts.
Think of a context as single instance of a state -  you can _set_ or _get_ anywhere in your React tree
ref: https://react.dev/learn/passing-data-deeply-with-context#

Your context in this case is something like `AppConfig`, holding app configuration info.
The intent is the default value of `AppConfig` should be `defaultContextValues` and then on line 58 we update `AppConfig` value with the result of our "get runtime var" code.

Currently it's creating two individual contexts.


An example from `rdpc-ui`
https://github.com/icgc-argo/rdpc-ui/blob/develop/src/app/hooks/AppProvider.tsx#L40

2023-09-13 18:05 UTC, ciaranschutte commented
verified runtime vars with a single `npm run build`
then running `npm run start` => TEST_RUNTIME_VAR is default value
then running `TEST_RUNTIME_VAR=working npm run start` => TEST_RUNTIME_VAR is "working"

2023-09-13 18:06 UTC, ciaranschutte approved these changes

2023-09-13 18:07 UTC, ciaranschutte commented
@samrichca couple of suggestions but runtime variables are working

2023-09-14 14:36 UTC, merged