🛂 371 - create auth middleware to parse bearer token from headers
OHCRN/platform pull request #508
Opened 2024-03-22 17:43 UTC by anncatton

## Description of Changes

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-03-22 20:05 UTC, anncatton commented on apps/consent-api/src/config.ts
> +		auth: {
For now the middleware will return a 500 server error if the key is missing, can the server fail if the key isn't retrieved + set?

2024-03-22 21:04 UTC, mistryrn reviewed
Looks great! Will have to think about that naming and also the handling of the keycloak public key in DEV/QA/etc, but I like this approach! Very clean stuff 🙂

2024-03-22 21:04 UTC, mistryrn commented on apps/consent-api/src/routers/participants.ts
> +router.get('/:id', withAuth, async (req, res) => {
Yeah I get what you're saying here. Almost feels more like a `GET /users` but not quite. Technically it is still the Participant as the entity, but we're getting it by `keycloakId` so 🤔 

Will have to think about this for sure!

2024-03-25 17:28 UTC, joneubank commented on apps/consent-api/src/middleware/auth.ts
> +			keycloakId?: string;
this is the ID of the keycloak? or is it the subject ID taken from the keycloak auth token?

Feels like ambiguous naming.

2024-03-25 17:30 UTC, joneubank commented on apps/consent-api/src/middleware/auth.ts
> +};
These seem like common utils that could be made generally available. No reason to overly refactor before there is a need, but you should keep an eye open as you keep coding and reviewing code for other places where these operations are done. Its possible we'd want to add these to a common package in the future so we can reuse this logic.

2024-03-25 17:31 UTC, joneubank commented on apps/consent-api/src/middleware/auth.ts
> + * @example
`@example` is a great feature of JSdoc comments.

Thanks for JS doc on the middleware @anncatton

2024-03-25 17:44 UTC, joneubank commented on apps/consent-api/src/middleware/auth.ts
> +				return res.status(500).json(ServerErrorResponse('Unexpected error'));
Is this the correct error message? This is an auth error, the error is expected, its caused by the bearer token being missing.

2024-03-25 18:18 UTC, joneubank commented on apps/consent-api/src/routers/participants.ts
> +router.get('/:id', withAuth, async (req, res) => {
If you are getting the `keycloakId` from the Authorization token, is it not just a request to GET self? Like, you arent actually requesting by ID, you are just able to retrieve information related to the user indicated in the provided token.

2024-03-25 18:26 UTC, anncatton commented on apps/consent-api/src/routers/participants.ts
> +router.get('/:id', withAuth, async (req, res) => {
ya exactly...i used this existing endpoint for the sake of convenience, but it was created when we were still just picturing the most straightforward REST setup. 
We do actually have a `/user` router which i forgot existed...maybe i can move this initial JWT setup there https://github.com/OHCRN/platform/blob/develop/apps/consent-api/src/routers/user.ts#L34

2024-03-25 18:28 UTC, anncatton commented on apps/consent-api/src/middleware/auth.ts
> +			keycloakId?: string;
yeah good point...at this stage it is the `sub` from the jwt. it becomes `keycloakId` in the ohcrn backend context

2024-03-28 12:04 UTC, anncatton commented on apps/consent-api/src/config.ts
> +		auth: {
Server will fail to start if the `keycloakPublicKey` is an empty value

2024-04-02 20:38 UTC, mistryrn reviewed
Looks good! I like the new changes to the middleware and handling the public key fetch. Most of my comments are just places where we can probably use just the "static" config instead of having to call the full async app config function 🙂

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/authConfig.ts
> +		console.error(err);
Should we be using the `logger` here instead of `console`?

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/middleware/auth.ts
> +		req.keycloakSubjectId = verifiedToken.sub;
Thanks for calling this out. Should we see how we get on with the registration flow and then make a decision on adding this?

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/middleware/recaptcha.ts
> +	const config = await getAppConfig();
Should we use the static config here since we're only grabbing the recaptcha key?

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/routers/user.ts
> +	// TODO: return user info - from decoded token?
That's fair – this is a good candidate for testing out the `withAuth` middleware, plus we have a follow-up ticket to actually implement the `/user` endpoint: https://github.com/OHCRN/platform/issues/167

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/server.ts
> +	const appConfig = await getAppConfig();
Similarly to the previous example – do we need the full app config here, or should we just use the static one? I think the `appConfig` var here gets passed into the `App` function in src/index.js and the only config value it uses is the `express.port`: https://github.com/OHCRN/platform/blob/3bcb2ff664d69c54d25550c34bbaeddb6c1a168a/apps/consent-api/src/index.ts#L50

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/services/create.ts
> +	const { dataMapperUrl } = await getAppConfig();
If we're just grabbing the `dataMapperUrl`, maybe we can get away with just the static config?

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/services/create.ts
> +	const { dataMapperUrl } = await getAppConfig();
Same comment as above 🙂

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/services/search.ts
> +		const { dataMapperUrl } = await getAppConfig();
Same as above 🙂

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/src/services/search.ts
> +		const { dataMapperUrl } = await getAppConfig();
Same as above 🙂

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/tests/config.ts
> +	// Need to stub KEYCLOAK_PUBLIC_KEY to prevent the AuthConfig from throwing an error, because there is no external fetch for the public key in testing
Thanks for calling this out 👍

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/tests/routers/invites.spec.ts
> +		const appConfig = await getAppConfig();
I wonder if we can use the static config in these tests too?

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/tests/routers/participants.spec.ts
> +		const appConfig = await getAppConfig();
Same as above 🙂

2024-04-02 20:38 UTC, mistryrn commented on apps/consent-api/tests/routers/steps/informed-consent.spec.ts
> +		const appConfig = await getAppConfig();
Same as above 🙂

2024-04-02 20:38 UTC, mistryrn commented on README.md
> +| `consent-api` | `KEYCLOAK_PUBLIC_KEY`             | Public key for Keycloak JWT parsing
I suppose these are both technically optional if the presence of one can make the other optional? 🤔 I reformatted these lines and updated the descriptions to include the "Required if X not provided" parts. What do you think?

```suggestion
| `consent-api` | `KEYCLOAK_REALM_PATH`         | URL for fetching Keycloak public key. Required if `KEYCLOAK_PUBLIC_KEY` is not provided.                                                                                                                                                                | `string`  | Optional |                                                                                                                                                                |
| `consent-api` | `KEYCLOAK_PUBLIC_KEY`         | Public key for Keycloak JWT parsing. Required if `KEYCLOAK_REALM_PATH` is not provided.                                                                                                                                                                 | `string`  | Optional |                                                                                                                                                                |
```

2024-04-03 19:09 UTC, anncatton commented on apps/consent-api/src/server.ts
> +	const appConfig = await getAppConfig();
setting the full AppConfig here so that the auth settings are instantiated on server start

2024-04-03 19:38 UTC, mistryrn commented on apps/consent-api/src/server.ts
> +	const appConfig = await getAppConfig();
Ah, that makes sense. Thanks!

2024-04-04 11:58 UTC, anncatton commented on apps/consent-api/src/authConfig.ts
> +		console.error(err);
oh wait nope, cuz logger uses staticConfig which is not initialized yet

2024-04-04 11:58 UTC, anncatton commented on apps/consent-api/src/middleware/auth.ts
> +		req.keycloakSubjectId = verifiedToken.sub;
yeah, i think we can add more in later tasks if we find we need extra data!

2024-04-04 12:10 UTC, mistryrn commented on apps/consent-api/src/authConfig.ts
> +		console.error(err);
Ah, gotcha. Thanks for confirming!

2024-04-04 12:20 UTC, mistryrn approved these changes
This looks good to me! Hopefully Jon can give it a look as well, but I'll approve for now anyway 🤠

2024-04-04 12:20 UTC, mistryrn commented on apps/consent-api/tests/config.ts
> +	// using the full AppConfig here because the tests use a mock App instance
Thanks for calling this out 👍

2024-04-08 14:17 UTC, joneubank requested changes
This is all very good and functionally we're basically good to go.

Most of my feedback is minor code organization things, but I am requesting changes cause I would like to simplify the config setup. Specifically:
- Do all the `process.env` access from the `config.ts` file and not from other specialized config files
- keep the main config object static (not async), probably doesnt need a rename
- make the authConfig details accessed through the async getter.
- keep both config objects separate. They can each have their own type.

The other place you should update is the modifications the middleware makes to the request object, I think making the middleware populate an optional object will help organize any future changes to our modification of the shared express request type (changes from this middleware adding more detail, or other middlewares also adding values).

2024-04-08 14:17 UTC, joneubank commented on apps/consent-api/src/server.ts
> +	const appConfig = await getAppConfig();
Maybe leave a comment in the code explaining this ;)

2024-04-08 14:17 UTC, joneubank commented on apps/consent-api/tests/config.ts
> +	// Need to stub KEYCLOAK_PUBLIC_KEY to prevent the AuthConfig from throwing an error, because there is no external fetch for the public key in testing
Perhaps creating a stub for the `authConfig.getPublicKey` function would be a more reliable way to ensure that unit tests don't actually fetch things, and allow us to test cases with and without this env property being set ;).

2024-04-08 14:17 UTC, joneubank commented on apps/consent-api/tests/config.ts
> +	// using the full AppConfig here because the tests use a mock App instance
I don't understand this comment.

2024-04-09 16:47 UTC, anncatton commented on apps/consent-api/src/middleware/recaptcha.ts
> +			`https://www.google.com/recaptcha/api/siteverify?secret=${secretKey}&response=${recaptchaToken}`,
I'll open a ticket for this so we don't forget

2024-04-09 16:47 UTC, anncatton commented on apps/consent-api/tests/config.ts
> +	// Need to stub KEYCLOAK_PUBLIC_KEY to prevent the AuthConfig from throwing an error, because there is no external fetch for the public key in testing
I ended up being able to delete the env stub once the async authConfig was removed from the main AppConfig object, and all the tests can rely on accessing the static config. Unless i'm missing something this should be ok to leave out entirely.

2024-04-09 16:54 UTC, anncatton commented on apps/consent-api/src/middleware/auth.ts
> +		req.keycloakSubjectId = verifiedToken.sub;
I added the expanded object to the request as you described, with an example `if req.authMiddleware, return success` on the `/user` endpoint. But i'm wondering, with the way the auth function is set up to throw errors if any step in the jwt validation/decoding fails, is it even necessary to have the extra check in the endpoint? I.e. `withAuth` would fail and return a 401 before it even got back to the endpoint, so if we get back to the `/user` handler we can assume the auth check succeeded? (this worked locally, but wondering if i am making a wrong assumption)

2024-04-09 16:56 UTC, anncatton commented on apps/consent-api/src/middleware/auth.ts
> + * If the token is valid, the "sub" value from the decoded token will be added to the Request object as the "keycloakId"
I added in the `keycloakSubjectId` as the `userId` - but i wasn't entirely sure what you intended that value to be, since you have the entire `verifiedToken` in the obj as well?

2024-04-09 18:13 UTC, joneubank approved these changes
Great work here Ann, thanks!

2024-04-09 19:10 UTC, merged