🗃️#532: Consent DAS: Add E-Signature Model to Prisma Schema
OHCRN/platform pull request #537
Opened 2024-04-04 16:02 UTC by xusandrew

## Description of Changes

- Adds signature model to consent DAS prisma schema
- Adds `getSignatureById` and `createSignature` methods
- `/signatures` router with a POST at `/` and a GET at `/:participantId/:signatureId`
- Created some necessary req/res types in the types package, but will update in #533
- Tested using swagger/pgadmin

### Special Instructions
Before running these changes, you will need to build
```
pnpm build
```

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-04-08 14:56 UTC, mistryrn requested changes
Really good stuff in here, just a few things missing because my requirements/examples didn't contain everything!

Requesting a few small changes here, mainly just to reference the Clinician Invite flow as an example since we had implemented our full validation and error handling by that point.

2024-04-08 14:56 UTC, mistryrn commented on apps/consent-das/prisma/schema.prisma
> +  participantId        String?
Apologies, I just noticed I had this in the ticket as just `participantId (String)`, but it should be required as well. Do you mind updating this to be required?

2024-04-08 14:56 UTC, mistryrn commented on packages/types/src/services/consentDas/requests/Signature.ts
> +});
We'll need a request object schema for the `POST` request as well, containing:
- [ ] participantId
- [ ] signature
- [ ] authenticationMethod
- [ ] createdAt

2024-04-10 16:10 UTC, mistryrn reviewed
Thanks for getting these changes in so quickly! It's looking good, just a couple more small changes and we should be good to go with this 🙏

2024-04-10 16:10 UTC, mistryrn commented on apps/consent-das/src/services/create.ts
> +	participantId?: string;
Let's make `participantId` required here and update the JSDoc comment above 🙂 
```suggestion
	participantId: string;
```

2024-04-11 13:13 UTC, anncatton requested changes
Lots of good stuff here Andrew! 

The changes for the migrations and the get + create behaviour i'd like to see done in this PR, plus adding the base type for Signature.

For the other type stuff I'm good with that being in #533 , but i'd like to add `TODO`s wherever we're postponing work so it's very clear what's still to be done.

2024-04-11 13:45 UTC, xusandrew commented on apps/consent-das/prisma/migrations/20240404135907_add_signature_model/migration.sql
> +CREATE TABLE "Signature" (
very weird i saw this too!

2024-04-11 14:36 UTC, mistryrn reviewed
Just following-up on Ann's review, let's discuss more in person when we're all in office

2024-04-11 14:36 UTC, mistryrn commented on apps/consent-das/prisma/schema.prisma
> +  authenticationMethod String
Good catch! Yes, let's add a composite ID constraint here too 🙂

2024-04-11 14:36 UTC, mistryrn commented on apps/consent-das/src/services/search.ts
> +	const participantResult = await getParticipantById(participantId);
Yeah, my bad – that's on me. I was referencing `participantResponses` too heavily while creating the ticket when the behaviour for the `/signatures` router is different.

The Consent DAS endpoints we’ll need for the `/signatures` router are:
- `POST /`  — create signature
- `GET /:participantId` — get all signatures for participant, sorted by `createdAt` date

Based on this, the search function should return an array of signatures objects for a given participant and could probably be called `getParticipantSignatures` instead to make things clear.

At the Data-Mapper layer we will then pick the latest signature (if any) from the array, and return that to the Consent-API, but that's not part of this ticket.

2024-04-12 19:18 UTC, anncatton reviewed
Nice work! I've added some more suggestions for error handling and a bit of refactoring

2024-04-12 19:18 UTC, anncatton commented on apps/consent-das/src/services/create.ts
> +				}
i ran into this just by using the default `participantId` in swagger when testing locally - can you add a block to handle an error on the participantId? prisma will throw foreign key constraint error (code `P2003`), which just means the `participantId` can't be found in the consent DAS `Participant` table. This error can be `PARTICIPANT_DOES_NOT_EXIST`, and you can update the `CreateSignatureFailureStatus` type to include that. Then just add in that case on the endpoint like you've done with `SIGNATURE_EXISTS`.

This is somewhat similar to what you were trying out earlier with the query for the participantId in the Participant table before the create query, but this way we can take advantage of the errors Prisma is giving us! We don't actually have this in the participant Response flow but it may be worth adding in a separate task.

I was looking up what HTTP error makes sense here and it *seems* like a 409 might be appropriate? https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409 (my first intuition was 400 but i don't think that's right). what do you and @mistryrn think?

2024-04-12 19:18 UTC, anncatton commented on packages/types/src/services/consentDas/responses/Signature.ts
> +	signature: z.string(),
See my above comment about extending the base with an additional subtype.

2024-04-17 19:20 UTC, anncatton reviewed
looking great Andrew! Just 2 smol changes needed.

2024-04-17 19:20 UTC, anncatton commented on apps/consent-das/src/routers/signatures.ts
> +					return res.status(404).json(NotFoundErrorResponse(signature.message));
i chatted with @mistryrn on this, let's make this a 400 error. The error message can stay the same.

2024-04-18 15:00 UTC, anncatton approved these changes
Great work Andrew! 🚀

2024-04-18 15:05 UTC, merged