FileStorage service for Consent-API and example upload endpoint
OHCRN/platform pull request #553
Opened 2024-04-12 17:39 UTC by joneubank

## Description of Changes

Adding ability to upload files through the consent API.

### Consent API
- Added a new FileStorage client to provides upload and download access to a file storage system based on provided system configuration
  - Written to be agnostic of file storage software
  - Created an S3 compatible implementation
- Files router provides an upload file endpoint
  - Generates a unique (nanoid) ID for the file then sends to file storage
  - Has configurable max accepted file size (set to 5MB by default)

### Docker Compose
- Added minio as a FileStorage system
  - Adds some top level env configs to provide root user and password, plus consent-api bucket to be created by default

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-04-15 15:28 UTC, mistryrn reviewed
Thanks for tackling this, really appreciate it! Awesome stuff in here. I know you're still working on it, so just a few smol documentation-related comments for now 🙂

2024-04-15 17:49 UTC, anncatton reviewed
Unsurprisingly looks awesome! Atm i don't have much feedback beyond typos...does look like the linter will need to be run before final merge. 
I was looking for an issue on the next-auth repo that clearly matched the `AUTH_URL` issue we're running into when not using the default `/api` path, haven't found anything yet. I'll link it in a comment here when I do

2024-04-15 17:49 UTC, anncatton commented on apps/consent-api/src/routers/files.ts
> +			case 'NetworkError': {
if this is just a general server 💥 we can use `SYSTEM_ERROR` here to match how other endpoints are set up

2024-04-15 17:49 UTC, anncatton commented on apps/consent-api/tests/environmentSetup.ts
> +process.env.DATA_MAPPER_URL = 'placeholder';
🙏

2024-04-15 17:49 UTC, anncatton commented on apps/consent-api/src/services/fileStorage/s3Client.ts
> + * would result in tagging hte filename as `file` and the creation of a new tag `unexpected:tagging.png`. After sanitization this would
`hte` -> `the`

2024-04-15 17:49 UTC, anncatton commented on apps/consent-api/src/services/fileStorage/s3Client.ts
> + * Remove all special characters from an S3 tag value and replace them with an `_` symbol.
🎉

2024-04-15 17:49 UTC, anncatton commented on apps/consent-api/src/services/fileStorage/fileStorageClient.ts
> + * be returned if it exists, otehrwise this will initialize the client from the environment configuration.
`otehrwise` -> `otherwise`

2024-04-15 17:49 UTC, anncatton commented on apps/consent-api/src/config/environmentVariables.ts
> + */
thanks for adding all these utils! makes the config feel so much more solid

2024-04-16 14:19 UTC, joneubank commented on apps/consent-api/src/routers/files.ts
> +import { randomUUID } from 'crypto';
No it is not, nice catch.

2024-04-16 14:21 UTC, joneubank commented on apps/consent-ui/.env.schema
> +RECAPTCHA_SITE_KEY=dude-whats-my-key
Can we put the google test keys in the schema? If we are using public keys for testing then no harm including them here to accelerate local devs.

2024-04-16 14:26 UTC, joneubank commented on apps/consent-api/src/routers/files.ts
> +			case 'NetworkError': {
So this is the constant from the error enums for the `FileStorageService.uploadFile` which can be unique to that interface. I identified two outcomes: error while sending the file to the storage service, or success. NetworkError seemed a suitable name to capture the error.

I'll change it to an ALL_CAPS_CASE to be consistent though.

2024-04-17 13:10 UTC, anncatton reviewed
Just need to restore the original folder path for the next-auth `route.ts` so login works - i tested out on my local keycloak.

Not sure if those `vi.unstubAllEnvs();` are needed anymore now you've got that test env file being imported?
And if you can run the lint script that would be awesome! There's some import warnings.

2024-04-17 13:10 UTC, anncatton commented on apps/consent-api/tests/routers/invites.spec.ts
> +// Needs to import config first to prepare environment variables
thanks for the extra comment here

2024-04-17 13:10 UTC, anncatton commented on apps/consent-api/tests/routers/invites.spec.ts
> +		// vi.unstubAllEnvs();
are the commented lines needed anymore or can we delete?

2024-04-17 13:10 UTC, anncatton commented on apps/consent-api/tests/routers/participants.spec.ts
> +		// vi.unstubAllEnvs();
same question as above

2024-04-17 13:10 UTC, anncatton commented on apps/consent-api/tests/routers/steps/informed-consent.spec.ts
> +		// vi.unstubAllEnvs();
same as above!

2024-04-17 13:10 UTC, anncatton commented on apps/consent-ui/src/constants/internalPaths.ts
> +export const AUTH_API_PATH = '/api/auth';
still need to move the next-auth `route.ts` back into `/app/api/auth` so the auth route is happy

2024-04-17 13:10 UTC, anncatton commented on apps/consent-ui/src/middleware.ts
> +	if (pathname.startsWith(AUTH_API_PATH)) {
🙏

2024-04-17 13:10 UTC, anncatton commented on apps/consent-ui/src/middleware/apiProxy.ts
> +	console.log('session', session);
can remove this log?

2024-04-17 13:54 UTC, joneubank commented on apps/consent-api/tests/routers/invites.spec.ts
> +		// vi.unstubAllEnvs();
Should still be there, accidentally committed this change. Thanks for catching it.

2024-04-17 13:59 UTC, anncatton submitted a review, later dismissed
Beauty! Thanks @joneubank

2024-04-17 16:24 UTC, mistryrn requested changes
Just one smol change needed to the API proxy regex, but other than that it looks great!

2024-04-17 16:24 UTC, mistryrn commented on apps/consent-ui/src/middleware/apiProxy.ts
> +	const redirectPath = request.nextUrl.pathname.replace(/^\/api/, '');
I think this regex will need to be updated from `/api` that we've changed `PROXY_API_PATH` to `/consent-api`:
https://github.com/OHCRN/platform/blob/2f84a20b6308e261d2d24eba93d501a055136d14/apps/consent-ui/src/constants/internalPaths.ts#L25

Since the middleware/proxy is now being called based on `/consent-api` as the path:
https://github.com/OHCRN/platform/blob/2f84a20b6308e261d2d24eba93d501a055136d14/apps/consent-ui/src/middleware.ts#L55

Probably a simple fix like this (note you'll need to import `PROXY_API_PATH` as well):
```suggestion
	const proxyPathRegex = new RegExp(`^${PROXY_API_PATH}`);
	const redirectPath = request.nextUrl.pathname.replace(proxyPathRegex, '');
```

2024-04-18 14:05 UTC, mistryrn approved these changes
Tested locally and it's working great! Approved ✅ Let's just make sure we get the infra/env vars updated before merging so dev doesn't crash 🙂

Will follow up separately to coordinate that.

2024-04-19 17:44 UTC, anncatton approved these changes
🚀 🚀

2024-04-19 17:59 UTC, merged