🏷️ #554 3/3: replace assentFormIdentifier with acknowledgement on participant
OHCRN/platform pull request #574
Opened 2024-04-26 13:51 UTC by samrichca

## Description of Changes

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-04-26 13:53 UTC, samrichca commented on packages/types/src/entities/Participant.ts
> -			assentFormIdentifier: OptionalString,
removing from ParticipantIdentityBase because it's used in pi-das

2024-04-26 13:55 UTC, samrichca commented on packages/types/src/services/consentApi/requests/ClinicianInvite.ts
> -		message: 'Invalid assentFormAcknowledged value provided for consentGroup',
making error messages consistent

2024-04-26 15:42 UTC, samrichca commented on apps/data-mapper/src/services/create.ts
> -			assentFormIdentifier,
- remove identifier from create participant in PI DAS
- add acknowledged to create participant in consent DAS

2024-04-29 16:45 UTC, anncatton requested changes
With schema changes, plz run the migration and test the flow locally before opening the PR for review.
For now, I've tried it locally with the migration applied and the response from Data Mapper returns a validation error, because a `null` is returned when there is no assent acknowledgement. A couple things need to happen to correct that:
- the `null => undefined` transform needs to be added to the `ConsentCreateParticipant` type in the data-mapper service. this is used with `safeParse` to apply the transform (see [this diagram](https://github.com/OHCRN/platform/blob/develop/docs/diagrams/types-schema-flow.md) for a reference on this kind of flow)
- a parsing check needs to be added to the `createParticipantConsentData` service call in the data-mapper `services/das/consent.ts` file. Plz reference the approach in `createInviteConsentData` https://github.com/OHCRN/platform/blob/develop/apps/data-mapper/src/services/das/consent.ts#L55.

I've added some other comments, but I'll finish the rest of the review when the above changes are added.

2024-04-29 16:45 UTC, anncatton commented on packages/types/src/services/dataMapper/requests/CreateParticipantResponse.ts
> +	assentFormAcknowledged: z.literal(true).optional(),
this type is for the participant response to a consent question in the wizard, the assent is not a part of that flow

2024-04-29 16:45 UTC, anncatton commented on packages/types/tests/utils/conditionalFields.spec.ts
> -	describe('hasRequiredAssentFormIdentifier', () => {
let's leave these tests in with the util for now

2024-05-01 19:37 UTC, anncatton reviewed
Just a typo to fix and then i think is good to go!

2024-05-01 19:37 UTC, anncatton commented on packages/types/src/services/dataMapper/responses/ConsentCreateParticipant.ts
> +	assentFormAcklowedged: z
little typo here `assentFormAcknowledged` 🙂

2024-05-03 13:02 UTC, anncatton approved these changes
🚀

2024-05-03 13:57 UTC, merged