#707: axios on client side
OHCRN/platform pull request #716
Opened 2024-06-19 01:24 UTC by samrichca

## Description of Changes

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-07-03 16:59 UTC, joneubank requested changes
This is amazing work and will be a big boon for future work. Consequently, I got a bit picky on some type points and naming so we can have a solid foundation to work off of. Looking forward to the final version (not a lot of changes to get there :) )

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/hooks/useCreateConsentApiProxy.tsx
> +	const createDataRequest = async (data: V): Promise<HandledResponse<T>> => {
This function gets passed around quite a bit, for a specific example we can look at `ConsentRecontactFormWrapper` which passes it to `ConsentRecontactForm`. This means we need to use the **type** of this function quite a bit, like in the props definition for `ConsentRecontactForm`.

We should export a generic type to help us with this:

```ts
export type DataRequestHandler<RequestBody, ResponseBody> = (data: RequestBody) => Promise<HandledResponse<ResponseBody>>;
```

Then you can use this when declaring the props for a component:

```ts
const ExampleComponentWithDataSubmission= ({
	children,
	createHandler,
	createLoading,
}: {
	children: ReactNode;
	createHandler: DataRequestHandler<ExampleRequest, ExampleResponse>;
	createLoading: boolean;
}) => { 
  // ...
}
```

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/constants/externalPaths.ts
> +export type ConsentApiPath = (typeof API)[ConsentApiPathKeys];
We have a nice utility for this:

```ts
import type {  Values } from "types/common";

// ...

export type ConsentApiPath = Values<typeof API>;
```

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/components/views/ConsentWizard/ConsentRecontact/ConsentRecontactForm/ConsentRecontactFormWrapper.tsx
> +}) => {
Consider using `PropsWithChildren<{/* your props */}>` instead of manually declaring the type of the children.

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/components/views/ConsentWizard/ConsentRecontact/ConsentRecontactForm/index.tsx
> +	) => Promise<HandledResponse<CreateConsentRecontactResponse>>;
See comment about creating a generic type to represent this handler function, will make reading the props much easier.

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/components/views/ConsentWizard/ConsentResearchParticipation/ConsentResearchParticipationForm/index.tsx
> +			);
When I saw this I assumed it was a function that only created logs when we are in a non-production environment, presumably based on a config setting. The reality his that this is just very verbose logging that will also run in production. We should remove this logging or add controls that it will only occur in a dev environment.

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/services/api/axios/client/catchAxiosError.ts
> +const DEFAULT_ERROR = 'Something went wrong';
`DEFAULT_ERROR_MESSAGE`

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/services/api/axios/client/catchAxiosError.ts
> +	}
Pretty good unknown type handling here. Because we know our error is coming from axios we can simplify this quite a bit thanks to `axios.isAxiosError()`

```ts
import { isAxiosError } from 'axios';

// ...

	if (isAxiosError(error)) {
		if (error.response) {
			return `${error.response.status} - ${error.response.data}`;
		} else if (error.request) {
			return String(error.request);
		} else {
			return DEFAULT_ERROR;
		}
	}
```

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/services/api/axios/client/catchAxiosError.ts
There are two files in the codebase called `catchAxiosError`, can we combine to one?

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/services/api/axios/client/axiosInterceptors.ts
Can we add some comments to this file/functions to explain that these functions are only meant to be used in lower environments? I had originally commented that we shouldnt be logging like this in the browser but then i saw that they are only called when we have Verbose config enabled.

Since the control over when this logging is used is not included in the logging itself, we should add some comments to explain the purpose and how this is controlled... but also to warn future devs not to use them without similar controls.

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/services/api/axios/client/axiosInterceptors.ts
Alternately let these functions read from the config directly and only run their console.log if the verbose mode is enabled. Then you can always include these and they only do something based on the config.

2024-07-03 16:59 UTC, joneubank commented on apps/consent-ui/src/services/api/axios/client/consentApiProxyClient.ts
> +const CONSENT_UI_URL = process.env.NEXT_PUBLIC_CONSENT_UI_URL || '';
Do we have config tools to use for this instead of reading directly from the `.env`? It is best to keep all of our environment variable references in a single place to simplify managing our configuration and environment. When the env interaction is spread throughout the app it becomes difficult to know how to configure it.

2024-07-03 17:41 UTC, samrichca commented on apps/consent-ui/src/hooks/useCreateConsentApiProxy.tsx
> +const useCreateConsentApiProxy = <T, V>({
good idea, we've been using `create` but I'd prefer `post` here because I'm not creating something, it's a generic post request.

2024-07-03 19:30 UTC, samrichca commented on apps/consent-ui/src/components/views/ConsentWizard/ConsentRecontact/ConsentRecontactForm/ConsentRecontactFormWrapper.tsx
> +}) => {
children is optional in PropsWithChildren so I explicitly define the children type when it's required

![image](https://github.com/OHCRN/platform/assets/3540896/083bfdb8-6323-41d0-a88b-82c78d6742db)

2024-07-03 20:05 UTC, anncatton commented on apps/consent-ui/src/components/views/ConsentWizard/ConsentResearchParticipation/ConsentResearchParticipationForm/index.tsx
> +			);
`qaLogger` was added just before our demo to help with qa testing, since we don't have full error handling yet. Not intended as a permanent feature! Might be good however to indicate this in function definition + a ticket `TODO`

2024-07-09 18:03 UTC, samrichca commented on apps/consent-ui/src/services/api/axios/client/catchAxiosError.ts
one is for the server-side requests which I don't want to update while I'm transitioning to client-side requests

I made a ticket for revisiting catchAxiosError for any remaining server-side requests https://github.com/OHCRN/platform/issues/752

2024-07-10 19:33 UTC, samrichca commented on apps/consent-ui/src/services/api/axios/client/consentApiProxyClient.ts
> +const CONSENT_UI_URL = process.env.NEXT_PUBLIC_CONSENT_UI_URL || '';
updated - getting the original env vars for consent UI URL & verbose logging from the hook, in the fetch hooks.

the NEXT_PUBLIC_ env vars have been removed

2024-07-10 19:38 UTC, samrichca commented on apps/consent-ui/src/services/api/axios/client/axiosInterceptors.ts
I don't think I can have them read from the config directly because it's client-side code and the client config is provided with hooks.

I added comments explaining when & how to use these.

2024-07-11 14:24 UTC, mistryrn reviewed
Lots of great work in here 🙂 Only found one log that can be removed in the `useConsentApiProxyGet` hook – other than that it looks great!

I left a comment for a discussion on whether or not we want to keep the verbose axios logging for the requests going from the client to the proxy, let me know what you think!

2024-07-11 14:24 UTC, mistryrn commented on apps/consent-ui/src/services/api/axios/catchAxiosError.ts
> +// https://github.com/OHCRN/platform/issues/752
Thanks for creating the ticket and linking to it here and in the comments

2024-07-11 14:24 UTC, mistryrn commented on apps/consent-ui/src/services/api/axios/client/consentApiProxyFetch.ts
> +	}
Just thinking out loud here, but I wonder whether we need/want verbose axios logging for these requests, since it's just going from the client to our internal proxy 🤔 Open question: is there any value in keeping the verbose axios logging here?

Maybe we could remove this from the `consentApiProxyFetch` if it doesn't add much value? That way on line 86 below, you can just use `axios` similarly to how we're currently doing it in https://github.com/OHCRN/platform/blob/b70fbc05c8b1f95f2a6dd645f78e97c52a4e1ad8/apps/consent-ui/src/app/consent-api/%5B...proxy%5D/route.ts#L83

And speaking of the actual proxy handler itself, maybe that's something that _could_ potentially benefit from verbose logging, since those requests will be going to/from something external (Consent API)?

I'm also fine with leaving things as-is since this setup is currently working 😛 But if we feel some of this isn't needed/adding much value then we may as well simplify

2024-07-12 17:02 UTC, mistryrn reviewed
Looks good! Just one optional arg that can be removed from the `ConsentApiProxyFetchArgs` type I think 🙂

2024-07-12 17:02 UTC, mistryrn commented on apps/consent-ui/src/services/api/axios/client/consentApiProxyFetch.ts
> +	VERBOSE_AXIOS_LOGGING?: boolean;
Can this be removed now as well?

2024-07-12 17:24 UTC, samrichca commented on apps/consent-ui/src/services/api/axios/client/consentApiProxyFetch.ts
> +	VERBOSE_AXIOS_LOGGING?: boolean;
thanks for catching that

2024-07-12 18:21 UTC, mistryrn submitted a review, later dismissed
Thanks for all the hard work that went into this one!

2024-07-12 20:32 UTC, joneubank submitted a review, later dismissed
Looks great. One suggestion.

2024-07-12 20:32 UTC, joneubank commented on apps/consent-ui/src/services/api/axios/client/consentApiProxyFetch.ts
> +}) => {
It might be nice to declare the response type here:
```ts
export const consentApiProxyFetch = async <TResponseBody>({
	baseUrl,
	body,
	headers,
	method = 'GET',
	params = '',
	path,
	responseSchema,
}: ConsentApiProxyFetchArgs<TResponseBody> & {
	body?: AxiosRequestConfig['data'];
	method?: Method;
}): Promise<Result<TResponseBody, 'SYSTEM_ERROR'>> => {
```

Reasons for this are:
- ensures there are no branches in this function that fail to return a Result
- ensures all successes return the correct data
- Makes it obvious what error conditions need to be handled.

2024-07-12 21:13 UTC, joneubank approved these changes

2024-07-14 23:23 UTC, merged