👽 💄  #742: register page client-side API requests
OHCRN/platform pull request #763
Opened 2024-07-17 15:45 UTC by samrichca

## Description of Changes

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-07-17 15:50 UTC, samrichca commented on apps/consent-ui/src/services/api/axios/client/consentApiProxyFetch.ts
> +	const reqUrl = urlJoin(baseUrl, `${path}${params}`);
add params to URL

the path has to come from the consent API paths object, so params are separate

2024-07-17 15:52 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +		if (isActive) {
for our current purposes,  I think resetting this hook's state if the hook isn't meant to be used should be OK.

2024-07-17 15:52 UTC, samrichca commented on apps/consent-ui/src/components/views/Register/index.tsx
> +	const { translate, translateNamespace } = getTranslation(currentLang);
RegisterFormWrapper was a server component. I made it a client component to match the consent wizard steps, and moved the translations up to Register/index.tsx

2024-07-17 15:54 UTC, samrichca commented on apps/consent-ui/src/components/views/Register/RegisterForm/RegisterFormWrapper.tsx
> +				inviteAccepted: !!getData.data.inviteAccepted,
I don't know what happened here with the types, if anyone has ideas let me know.

2024-07-18 13:52 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
>  }) => {
Should we add a similar `isActive` parameter to the POST version?

2024-07-18 13:54 UTC, joneubank requested changes
Updating review because i had a thought on the isActive implementation that should be reviewed.

2024-07-18 13:54 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	isActive = false,
I think we should make this `true` by default. I think we would expect the hook to work by default, and this parameter is a mechanism to disable it. Also, we want the existing proxy get hooks to continue to send without having to go back through and set isActive to true on all of them.

2024-07-18 14:48 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	isActive = false,
I think I finally pinned down the issue I'm having with this interface... can we change this property to be `disabled` instead of `isActive`? Its a property we set to stop the hook from running, its not a check on whether the hook is active or not.

So invert the logic I described above, disabled would be `false` by default so that this hook runs unless it gets set to disabled.

2024-07-18 16:07 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
>  }) => {
definitely but I'm going to add it on a PR with a POST request

2024-07-18 16:42 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	isActive = false,
good catch, default true was the intended behaviour

2024-07-18 18:40 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	isActive = false,
on second thought, I'm going to change this hook so it returns a function we call as needed, like the post hook.

I want to use the get function conditionally here and based on user action on the dashboard page, so it'd be good to have more control

2024-07-18 20:11 UTC, joneubank approved these changes

2024-07-19 15:05 UTC, merged