👽 💄 #742: migrate register GET /invite request to client-side
OHCRN/platform pull request #769
Opened 2024-07-19 19:26 UTC by samrichca

## Description of Changes

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-07-19 20:10 UTC, samrichca commented on apps/consent-ui/src/components/views/ConsentWizard/ConsentRecontact/ConsentRecontactForm/ConsentRecontactFormWrapper.tsx
> +		getData.getRequest();
for the consent steps I left the naming as `getData.x` `createData.y` because we're getting and creating the same data.

2024-07-19 20:10 UTC, samrichca commented on apps/consent-ui/src/components/views/Register/RegisterForm/RegisterFormWrapper.tsx
> +		data: inviteData,
the registration page has separate invite & register operations so I renamed/destructured the hook's contents.

2024-07-23 19:22 UTC, joneubank requested changes
I generally prefer this interface to the "disabled" control.

Can we also apply the same pattern to the POST hook?

2024-07-23 19:22 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	return { data, error, getRequest, loading, reset, setData, setError, setLoading };
We probably shouldn't be exposing setData/Error/Loading , these are used internal to the hook.

2024-07-23 19:22 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	};
This is incomplete... if the request is being awaited, then after you reset everything to undefined the request could complete updating all the data again... even though we weren't loading. This needs to also cancel the axios request. I think.

2024-07-23 21:01 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	};
good idea, added axios request cancellation to the get & post hooks in order to make `signal` a required parameter in the underlying fetch function

2024-07-31 19:58 UTC, samrichca commented
Closing due to Jenkins issues. New PR: https://github.com/OHCRN/platform/pull/769

2024-07-31 19:58 UTC, closed without merging