✅#799: add institutional email allowlist
OHCRN/platform pull request #810
Opened 2024-08-20 19:53 UTC by samrichca

## Description of Changes

This PR adds an allowlist for institutional email address domain names, so that clinician invites can only be initiated by people with appropriate email addresses.

### Types
- Add list of allowed email domains
- Update schemas for clinician invite consent API request & the form with a refinement on the clinician email field
- Update tests to check for specific errors

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-08-20 20:57 UTC, samrichca commented on packages/express-request-validation/tests/index.spec.ts
> -		const requestHandler = vi.fn<Parameters<RequestHandler>, ReturnType<RequestHandler>>((req) => {
this produced an error when I upgraded to vitest 2

2024-08-20 20:58 UTC, samrichca commented on package.json
> +		"vitest": "^2.0.5"
this update is needed to continue using the vitest vscode plugin.

2024-08-21 15:44 UTC, joneubank requested changes

2024-08-21 15:44 UTC, joneubank commented on packages/types/src/common/utils/clinicianInstitutionalEmail.ts
> +];
This is hardcoded into a service that is shared across every module application we run. If we need to change this list, we're going to need to rebuild and deploy all of our services that validate emails.

To some extent this is unavoidable... but I think it may be worth moving this validation only onto the API service. We only need to validate emails as they are submitted to us, once they are inside the system we should accept them without rechecking the domain.

Would you consider changing the approach her to just being an input validation that is done on specific api endpoints instead of modifying our email rules?

2024-08-27 18:20 UTC, anncatton reviewed
Added some comments + the prisma version fix merged to develop created a conflict in the lockfile.

2024-08-27 18:20 UTC, anncatton commented on apps/consent-api/src/routers/invites.ts
> +		message: 'Clinician institutional email domain is not allowed',
we can still put the error in the `refinementErrorMessages.ts` file

2024-08-27 19:42 UTC, anncatton approved these changes
thanks for the updates @samrichca !

2024-08-27 19:42 UTC, anncatton commented on apps/consent-api/src/routers/invites.ts
> +		message: clinicianInstitutionalEmailDomainNotAllowed,
🙏

2024-08-28 02:40 UTC, joneubank submitted a review, later dismissed
Works fine. Left suggestion for improvement.

2024-08-28 02:40 UTC, joneubank commented on apps/consent-api/.env.schema
> +CLINICIAN_INSTITUTIONAL_EMAIL_DOMAIN_ALLOWLIST=
You may want to include an example value to show how to format this list.

2024-08-28 02:40 UTC, joneubank commented on apps/consent-api/src/utils/checkClinicianInstitutionalEmailDomain.ts
> +	return allowList.includes(clinicianInstitutionalEmailAddress.split('@')[1] || '');
If the env value is formatted poorly, for example two spaces back to back like `gmail.com  yahoo.com`, then the domain `''` will be allowed.

This isn't particularly bad but its an incomplete check. We should better validate and check our env value by filtering out empty values. We should also perform this parsing on start up, theres no reason to perform the split operation every time a user submits a form.

2024-08-28 15:14 UTC, samrichca commented on apps/consent-ui/src/services/api/axios/client/catchAxiosError.ts
> +			return `${error.response.status} - ${JSON.stringify(error.response.data)}`;
fix issue where errors were returning e.g. `401 - [Object object]`

2024-08-28 15:15 UTC, mistryrn reviewed
Looks good! I agree with Jon's comments, left a suggestion for the examples.

2024-08-28 15:15 UTC, mistryrn commented on apps/consent-api/.env.schema
> +CLINICIAN_INSTITUTIONAL_EMAIL_DOMAIN_ALLOWLIST=
I like Jon's suggestion of including example values, maybe we can include some example/dummy domains in here to make local setup and testing easier?

Looks like `example.com`, `example.net`, `example.org` etc are reserved domain names that we can use without worry: https://en.wikipedia.org/wiki/Special-use_domain_name#Reserved_domain_names

2024-08-29 15:00 UTC, mistryrn approved these changes
Thanks for updating, looks good!

2024-08-29 18:24 UTC, merged