fix guardian name
OHCRN/platform pull request #819
Opened 2024-08-29 18:03 UTC by samrichca

## Description of Changes

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-08-29 18:04 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	| { type: 'error'; payload: { error: any } };
if I change `error: any` to `error: unknown`, I get errors

2024-08-29 18:04 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	const reducer = (
I tried to move this outside of the hook, but I had trouble getting the generics to work.

2024-08-29 18:04 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +	const getRequest = useCallback(async (): Promise<ResponseBody | undefined> => {
typo

2024-08-29 18:05 UTC, samrichca commented on packages/express-request-validation/tests/index.spec.ts
> +		const requestHandler = vi.fn((req) => {
fixing build issue with vitest upgrade

2024-08-29 18:34 UTC, joneubank requested changes
This is a significant improvement, I like this model a lot.

2024-08-29 18:34 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +};
What is the value of this state before any data is loaded? It would have no data or error, which is only legal according to this definition since `error: unknown` is satisfied by `undefined`.

I might suggest instead:
```
type ReducerState<TResponseBody> =
	| {
			loading: true;
	  }
	| ({
			loading: false;
	  } & ({ data: TResponseBody } | { error: unknown }) & {
				loading: boolean;
			});
```

And set the default to:

```ts
const reducerDefaultState = { loading: true };
```

This works so long as you don't need a way to differentiate "request not started" and "request currently underway". If you do, then consider using state as an enum with options `'LOADING' | 'ERROR' | 'SUCCESS' | 'NOT_STARTED'` and a type like:

```ts
type RequestState = 'LOADING' | 'ERROR' | 'SUCCESS' | 'NOT_STARTED';
type ReducerState<TResponseBody> =
	| {
			state: 'NOT_STARTED'
	  }
	| {
			state: 'LOADING'
	  }
	| {
			state: 'ERROR',
			error: unknown
	  }
	| {
			state: 'SUCCESS',
			data: TResponseBody
	  };
```

2024-08-29 19:46 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGet.tsx
> +};
I like the idea of states. 

BTW most of our get requests happen right away on page load and some are triggered by the user, like consent PDF, so we have to account for both

2024-08-30 18:30 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGetReducer.tsx
> +export const ReducerStatus = z.enum(REDUCER_STATUSES);
I changed this to `status` to avoid conflicts with `state`

2024-08-30 18:31 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGetReducer.tsx
> +type ReducerState<TResponseBody> =
`data` and `error` have to be specified for all versions of state, or else when I use this hook I get errors in vscode that data & error aren't known properties.

2024-09-03 20:22 UTC, joneubank approved these changes
I think this is fine... The reducer syntax cause us to declare the properties with type `undefined` is really awkward but not strictly wrong.

2024-09-03 20:22 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGetReducer.tsx
> +	| { status: 'FAILURE'; data: undefined; error: any };
If a property is `undefined`, just don't include the property (`error` and `data` respectively).

2024-09-03 20:22 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGetReducer.tsx
> +	| { status: 'FAILURE'; data: undefined; error: any };
Is this done to simplify the reducer assignment/overwrite? Does the reducer only replace the values specified instead of completely replacing the stored value with the new object?

2024-09-03 20:22 UTC, joneubank commented on apps/consent-ui/src/hooks/useConsentApiProxyGetReducer.tsx
> +				};
Maybe this is a limitation of the reducer interface that I am about to learn (ie. maybe its not an overwrite but a merge value)... couldn't we just define the result as:

```ts
result = {
					data: action.payload,
					status: ReducerStatus.enum.SUCCESS,
				};
```

2024-09-03 20:32 UTC, anncatton reviewed
Are these changes connected to a ticket?

2024-09-04 14:52 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGetReducer.tsx
> +	| { status: 'FAILURE'; data: undefined; error: any };
when I left out undefined properties I got errors saying the properties were unknown.

the reducer overwrites all values

2024-09-04 14:53 UTC, samrichca commented
> Are these changes connected to a ticket?

it is now ;)

2024-09-04 14:59 UTC, samrichca commented on apps/consent-ui/src/hooks/useConsentApiProxyGetReducer.tsx
> +				};
if I don't make data & error known properties at all times, I get type errors:

![image](https://github.com/user-attachments/assets/256ed5ed-fc20-45a3-94f1-eaddf69572e9)

2024-09-06 17:38 UTC, joneubank approved these changes

2024-09-06 17:53 UTC, merged