💄 #287 Clinician Invite Page: Add Link to Actual Assent Form File (PDF)
OHCRN/platform pull request #828
Opened 2024-09-06 18:23 UTC by shailikadakia-oicr

Converted assent form to a pdf, updated the assets dictionary for fr and en, and updated the link in clinician invite form to open assent form

## Description of Changes
Added `assentFormPdf` to the assetUrls dictionary. This is imported into the `inviteFormText Dictionary` which adds to the text dictionary in `ClinicianInviteFormComponent`. This allows fr and en users to view the assent form in their respective languages.

Users can now view the assent form and download it. 

## PR Readiness Checklist

- [x] "Expected Outcome(s)" in ticket have been met
- [x] Ticket number included in PR title
- [ ] Connected ticket to PR
- [x] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [x ] Manual testing completed
- [x ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] [Axe DevTools](https://www.deque.com/axe/browser-extensions/) "Full Page Scan" of updated pages passes without introducing new Critical or Serious issues (UI changes only)
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-09-06 18:30 UTC, samrichca commented on apps/consent-ui/src/i18n/locales/en/assetUrls.ts
> +	assentFormPdf: 'OHCRN_Assent-v2_14Dec2023_clean.pdf',
we're keeping dictionaries alphabetized to make sure english & french dictionaries match. I use this plugin here https://marketplace.visualstudio.com/items?itemName=ue.alphabetical-sorter

2024-09-09 13:26 UTC, shailikadakia-oicr commented on apps/consent-ui/src/i18n/locales/en/assetUrls.ts
> +	assentFormPdf: 'OHCRN_Assent-v2_14Dec2023_clean.pdf',
Thank you Sam! I've downloaded the plug-in and pushed the changes :)

2024-09-09 14:18 UTC, mistryrn requested changes
Looks great! One smol change request, other than that this should be good to go 🙂

2024-09-09 14:18 UTC, mistryrn commented on apps/consent-ui/src/components/views/Invite/ClinicianInviteForm/index.tsx
> +										<Link href={assentFormPdfUrl} prefetch={false}>
Let's make this PDF open in a few tab so the Clinician doesn't lose anything they may have already entered into the invite form when they click this link:
```suggestion
										<Link href={assentFormPdfUrl} prefetch={false} target="_blank">
```

2024-09-09 14:30 UTC, samrichca commented on apps/consent-ui/src/components/views/Invite/ClinicianInviteForm/index.tsx
> +										<Link href={assentFormPdfUrl} prefetch={false}>
thanks for pointing this out. we have it on another PDF link as well.

2024-09-10 14:43 UTC, mistryrn approved these changes
Looks good! Thanks for getting that change in 🙂

2024-09-10 15:55 UTC, merged