#857 Added link to contact page after patient invite
OHCRN/platform pull request #858
Opened 2024-09-17 13:57 UTC by shailikadakia-oicr

## Description of Changes

### Consent UI
- Added a link to https://ohcrn.ca/contact-us/ from `InviteSentNotification`

## PR Readiness Checklist

- [ ] "Expected Outcome(s)" in ticket have been met
- [ ] Ticket number included in PR title
- [ ] Connected ticket to PR
- [ ] Labels added to PR for service name (`consent-api`, `data-mapper`, etc...), type (`chore`, `documentation`, etc...), status (`draft`, `on-hold`, etc...) **if applicable**
- [ ] Manual testing completed
- [ ] Builds locally without errors or warnings
- [ ] Tests are updated (if required) and passing
- [ ] [Axe DevTools](https://www.deque.com/axe/browser-extensions/) "Full Page Scan" of updated pages passes without introducing new Critical or Serious issues (UI changes only)
- [ ] PR feedback has been addressed **if applicable**
- [ ] New environment variables added to `.env.schema` files, `README.md`
- [ ] Added copyrights to new files

2024-09-18 19:19 UTC, samrichca commented on apps/consent-ui/src/components/views/Home/notifications/InviteSentNotification.tsx
> +			<Link href="https://ohcrn.ca/contact-us/" prefetch={false} target="_blank">
please add this link to the external paths file

2024-09-19 15:02 UTC, samrichca requested changes

2024-09-20 18:46 UTC, shailikadakia-oicr commented on apps/consent-ui/src/components/views/Home/notifications/InviteSentNotification.tsx
> +			<Link href="https://ohcrn.ca/contact-us/" prefetch={false} target="_blank">
Thank you @samrichca I have added it to the dictionary :)

2024-09-23 19:19 UTC, samrichca commented on apps/consent-ui/src/components/views/Home/notifications/InviteSentNotification.tsx
> +			<Link href="https://ohcrn.ca/contact-us/" prefetch={false} target="_blank">
sorry, to clarify, we have a file for external paths: `apps/consent-ui/src/constants/externalPaths.ts`

please add this link here instead of the dictionary, and then i can approve your PR 👍

2024-09-23 20:59 UTC, shailikadakia-oicr commented on apps/consent-ui/src/components/views/Home/notifications/InviteSentNotification.tsx
> +			<Link href="https://ohcrn.ca/contact-us/" prefetch={false} target="_blank">
Ohh thank you for pointing that out! I've updated the files :)

2024-09-23 21:05 UTC, shailikadakia-oicr commented on apps/consent-ui/src/components/views/Home/notifications/InviteSentNotification.tsx
> +			<Link href="https://ohcrn.ca/contact-us/" prefetch={false} target="_blank">
Need to resolve conflicts tomorrow morning

2024-09-24 20:27 UTC, samrichca approved these changes

2024-09-25 13:08 UTC, merged