✨ Fetch consent-api version in footer
OHCRN/platform pull request #88
Opened 2023-09-12 20:49 UTC by alyssadsouza

- Added an endpoint to the consent-api health router for fetch the API version # from the package.json, which is then displayed in the consent-ui footer
- Installed Axios and introduced some new file structure in consent-ui for data fetching
  - `src/config` contains the AppConfig which will be reused throughout the UI for getting config / env vars → this will probably need to be updated after #48 gets merged
  - `src/constants` contains global constants, currently storing external path constants: the consent-api URL and endpoints, and API response type
  - `src/hooks` currently just contains the hook for fetching data from the new `health/version` endpoint
- Also added new directory in `common` for Consent API types: `common/service` for maintaining shared types to enforce shape of API response data

2023-09-12 23:26 UTC, ciaranschutte commented
one thing to be aware of with variables based on env vars eg. `apps/consent-ui/src/constants/externalPaths.ts`
this file will be statically built unless there's something preventing this

!remind me for more deetails

2023-09-13 16:22 UTC, anncatton reviewed
Great work! Just leaving some general comments for now that aren't related to all the env var stuff. As you mentioned there'll be likely changes from that, esp on the data fetch stuff, so let's leave the PR open for the time being.
Actually, let's convert this to a draft PR for now until everything is sorted! 🙂

2023-09-13 16:22 UTC, anncatton commented on apps/consent-api/src/routers/health.ts
> + * /health/version:
Had a discussion with @mistryrn on this, we're thinking it would be good to rename this router to `status` instead of `health`, and include both the health check (can leave hardcoded for now like in the base endpoint, as we don't have a real health check yet) and the version in the same endpoint, like `{ status: 'API is healthy', version: packageVersion }`. Apologies, I think you asked this exact question while doing the work on this ticket! Then we only need the base endpoint from this file, and we'll leave the `TODO` for the healthcheck.

2023-09-13 16:22 UTC, anncatton commented on apps/consent-ui/package.json
> +    "axios": "^1.5.0",
👍

2023-09-13 16:22 UTC, anncatton commented on apps/consent-ui/src/constants/externalPaths.ts
> +	VERSION: API_ROOTS.HEALTH + '/version',
For url concatenation, we like to use [url-join](https://www.npmjs.com/package/url-join) - it prevents missing/extra `/`s... a lifesaver! 😂 
It's already in the package.json so you can just import as `import urlJoin from 'url-join`

2023-09-13 16:22 UTC, anncatton commented on packages/common/src/service/Health/Health.ts
> +}
Seems like our linter/prettier is not adding newlines/formatting on save 🤔 Can you add a newline to the end of the file, and one of use can investigate why the formatter isn't working!

2023-09-13 16:22 UTC, anncatton commented on packages/common/src/service/Health/index.ts
> +export * from './Health';
same as above 🙂

2023-09-13 16:22 UTC, anncatton commented on apps/consent-api/tsconfig.json
> +    "resolveJsonModule": true,
i can see the nodemon complaints that you mentioned when i tried non-relative imports in the api...i'll poke around and see if i can figure out what's going on!

2023-09-15 14:41 UTC, alyssadsouza commented on apps/consent-api/tsconfig.json
> +    "resolveJsonModule": true,
fixed in #89!

2023-09-19 18:27 UTC, anncatton requested changes
Thanks for updating the router! I've requested a few more changes for the fetching, but the type importing stuff is not necessary on this PR - we can address later if needed!

2023-09-19 18:27 UTC, anncatton commented on apps/consent-api/src/routers/status.ts
> +import { APIStatus } from 'common/src/service/Status';
@mistryrn pointed this out to me, but we'll have to get these types to export correctly so that we can import nicely, i.e. `import { APIStatus } from 'common/service'` or even `import { APIStatus } from 'common'`. I was fiddling with the common build locally and haven't got it to work properly yet, so if necessary we can just add a `TODO` here to remind ourselves to fix, and not block the res of this work!

2023-09-19 18:27 UTC, anncatton commented on apps/consent-ui/src/constants/externalPaths.ts
> +export const API = {
👍

2023-09-19 18:27 UTC, anncatton commented on apps/consent-ui/src/constants/index.ts
> +export interface APIResponse {
I think specifically for `types` we're going to want to use `types.ts` files in the applicable directory, instead of putting them with constants. i'm undecided about how modular we want the types files to be but we can maybe decide as we get more things implemented  - or i @mistryrn has any thoughts/preferences for that?

2023-09-19 18:27 UTC, anncatton commented on apps/consent-ui/src/hooks/getAPIStatus.tsx
> +const axiosInstance = axios.create({
how would you feel about a dedicated file we can export a base axios instance from, and then we can reuse as needed?

2023-09-19 18:27 UTC, anncatton commented on apps/consent-ui/src/hooks/getAPIStatus.tsx
> +const getAPIStatus = async () => {
Apologies, I know I suggested earlier about creating a hook for this request, like the example in `dac-ui`! But looking at this now and where we call it, in a server component, i'm thinking we can simplify this somewhat and skip anything hooks-like. I'm thinking something like:
```
const getAPIStatus = async () => {
	const appClientConfig = await getAppClientConfig();
	const { CONSENT_API_URL } = getAppConfig(appClientConfig);

	return await axiosInstance
		.get(API.STATUS, { baseURL: CONSENT_API_URL })
		.then((res: AxiosResponse<APIStatus>) => {
			return res.data;
		})
		.catch((err: AxiosError<APIStatus>) => {
			console.error('Unable to receive consent-api status ⛔️: ', err);
			// we can decide on some custom error response, instead of just throwing an error and catching
			// so we have something to display in the case of an error
			const errorRes: APIStatus = {
				version: 'not found',
				status: 'API fetch failed',
			};
			return errorRes;
		});
};
```

And we can take advantage of the error and response types in Axios and customize with your `Status` type so that we can control the exact return type from this function.

2023-09-19 18:27 UTC, anncatton commented on apps/consent-ui/src/hooks/getAPIStatus.tsx
> +const getAPIStatus = async () => {
And then when the function is called in the `Versions` component, we can call it like:
`const { version } = await getAPIStatus()`
and maybe wrap the version `span` with `<Suspense fallback={<span />}>{...}</Suspense>`

2023-09-19 18:27 UTC, anncatton commented on apps/consent-ui/src/constants/index.ts
> +export interface APIResponse {
I think also in this particular case we don't need this `APIResponse` type as we can reuse what Axios provides. One thing I think could be useful would be adding a specific "version error" type where we have a static response we can return from the request if an error occurs, i.e.:
`{ version: 'Unavailable', status: 'Version unavailable' }`
Just an example, we maybe just leave the API version blank if the req fails 🤔

2023-09-19 21:17 UTC, alyssadsouza commented on apps/consent-api/src/routers/health.ts
> + * /health/version:
updated!

2023-09-19 21:22 UTC, alyssadsouza commented on apps/consent-api/src/routers/status.ts
> +import logger from '@/logger';
Sure! I'll do it in a separate PR.

2023-09-19 21:23 UTC, alyssadsouza commented on apps/consent-api/src/routers/status.ts
> +import { version } from '@/../package.json';
I don't have a preference either, unless @mistryrn disagrees I'll leave it as relative

2023-09-20 13:32 UTC, alyssadsouza commented on apps/consent-ui/src/hooks/getAPIStatus.tsx
> +const axiosInstance = axios.create({
I think it's a good idea since the base URL in the UI will always be the consent-api URL, so that's a good parameter to set in the base instance.

2023-09-20 13:37 UTC, alyssadsouza commented on apps/consent-ui/src/hooks/getAPIStatus.tsx
> +const axiosInstance = axios.create({
Although accessing the consent-api URL is asynchronous since we need the correct environment variable so that may be annoying to set.

2023-09-20 16:05 UTC, alyssadsouza commented on apps/consent-api/src/routers/status.ts
> +import { APIStatus } from 'common/src/service/Status';
added a TODO

2023-09-21 15:44 UTC, anncatton requested changes
Thanks for all the fixes! Just a couple cleanup requests. And penny for yours and @mistryrn 's thoughts on how to structure the api request portion

2023-09-21 15:44 UTC, anncatton commented on apps/consent-ui/src/hooks/getAPIStatus.tsx
> +const getAPIStatus = async () => {
Good call! Thanks for taking extra time with this. tbh i am still figuring out the whole server component approach so it's learning as we go 🙂

2023-09-21 15:44 UTC, anncatton commented on apps/consent-ui/src/hooks/getAPIStatus.tsx
> +const getAPIStatus = async () => {
one other thought here...since this function isn't a hook we should move it elsewhere. @mistryrn any thoughts on a nice way to structure this? i think it would also be good to move the `axios` instance creation out of `constants`, that's not really a fit either 🤔

2023-09-21 16:01 UTC, alyssadsouza commented on apps/consent-ui/src/hooks/getAPIStatus.tsx
> +const getAPIStatus = async () => {
Maybe just a separate directory `src/api`? Though might be a bit confusing since there's `src/app/api` for the env variables stuff.

2023-09-21 22:01 UTC, mistryrn requested changes
Sorry for taking so long to get through this 😅 This looks great!! Everything works as expected, and after spending **way** too long chatting with Ann about naming and organizing things, I've got a solution for the open conversations in the PR.

Apologies for making you move things around yet again, but this will be the last time for this PR (we promise)! 🙏 

Here's the new target structure:
```
.
└── consent-ui/
    └── src/
        ├── app
        ├── config/
        │   ├── appConfig.ts
        │   └── index.ts
        ├── constants/
        │   ├── externalPaths.ts
        │   └── index.ts
        └── services/
            └── api/
                ├── axiosClient.ts
                ├── status.tsx
                └── index.tsx
```

- [ ] move `getAppConfig.ts` to `/config/appConfig.ts`, create `/config/index.ts` to export everything so we can import from `@/config`, update imports
- [ ] move `constants/api.ts` to `services/api/axiosClient.ts`
- [x] move `hooks/getAPIStatus.tsx` to `services/api/status.tsx`, create `services/api/index.tsx` to export everything, update imports
- [ ] make Axios client in `services/api/axiosClient.ts` consent-api-specific (specify `baseUrl` in the config there, update requests that use it to no longer have to specify it in each request)

That should do it for this PR! Thanks so much for putting up with @anncatton and I!!

2023-09-22 14:05 UTC, mistryrn approved these changes
Looks great! 🚀🚀🚀

2023-09-22 15:37 UTC, anncatton approved these changes
Looks great! You can delete my comment in the version fetch call as it was just for my example, but approved! 🎉 🚀

2023-09-22 15:37 UTC, anncatton commented on apps/consent-ui/src/services/api/status.ts
> +			// we can decide on some custom error response, instead of just throwing an error and catching
can delete my comments 🙂

2023-09-22 15:43 UTC, merged