Feat/82 participant response prisma schema
OHCRN/platform pull request #92
Opened 2023-09-14 20:37 UTC by alyssadsouza

- Added the Participant Response create/read methods
- Seed data not necessary since responses will be created with users + questions via an api call later on

Note that this branch was created from #91 due to the existing schema in that branch, so the changes are compounded from that.

2023-09-17 15:21 UTC, anncatton requested changes
Thanks for adding this! Would you be able to change your base branch to your other feature branch so these changes are more clear? Github is smart and will update the base here back to `develop` once you merge in your first feature branch 🎉

2023-09-17 15:21 UTC, anncatton commented on apps/consent-das/src/service/create.ts
> +	submittedAt,
Won't need to pass `submittedAt` in, this date value should be generated in the db by the `now()` call

2023-09-19 14:12 UTC, alyssadsouza commented on apps/consent-das/src/service/search.ts
> +export const getParticipantResponses = async (): Promise<ParticipantResponse[]> => {
Updated this to take the `participantId`, `consentQuestionId`, and optional `ascending` parameters and returns the participant responses by participantId and consentQuestionId, and sorts by `submittedAt` in ascending order if ascending is true, otherwise descending order.

2023-09-19 15:43 UTC, alyssadsouza commented on apps/consent-das/src/service/search.ts
> +export const getParticipantResponse = async (
Updated it to take submittedAt as an optional parameter and if not provided, returns the most recent response.

2023-09-20 15:34 UTC, mistryrn approved these changes
Awesome stuff! :)

2023-09-21 14:43 UTC, anncatton commented on apps/consent-das/src/service/search.ts
> +	ascending?: boolean,
i think for this it would be better to have this arg as an optional `sortOrder` instead of naming it specifically to `ascending`...but having the default order as `desc` is 👍 

Prisma has a `SortOrder` type we can use, you can access it with the `Prisma` client you've imported in this file, i.e. `sortOrder: Prisma.SortOrder = Prisma.SortOrder.desc`, and then we can use `orderBy: { submittedAt: sortOrder }` in the find call

2023-09-21 14:46 UTC, anncatton commented on apps/consent-das/src/service/search.ts
> +export const getParticipantResponse = async (
ah good point, yes we probably wouldn't so this is a good solution! i think that's what i was thinking but i did not actually type that in my feedback 😂

2023-09-21 15:46 UTC, alyssadsouza commented on apps/consent-das/src/service/search.ts
> +	ascending?: boolean,
updated!

2023-09-21 15:52 UTC, anncatton approved these changes
🚀 🚀 🚀

2023-09-21 16:07 UTC, merged