💄📱 Implement landing page hero
OHCRN/platform pull request #98
Opened 2023-09-19 16:03 UTC by alyssadsouza

- Implemented hero with responsive styling
- Updated responsive styling for Footer to use the grid display so the sizing and arrangements are cleaner
- Added animations for Button component

<img width="1512" alt="Screenshot 2023-09-19 at 11 55 29 AM" src="https://github.com/OHCRN/platform/assets/70766739/db60312b-42e5-416f-b149-ad3274c6e378">
<img width="847" alt="Screenshot 2023-09-19 at 11 56 31 AM" src="https://github.com/OHCRN/platform/assets/70766739/051fa3f8-6122-4719-9b56-10871c5e5f8b">
<img width="400" alt="Screenshot 2023-09-19 at 11 57 12 AM" src="https://github.com/OHCRN/platform/assets/70766739/37f2c653-a131-4c89-9569-48e7ef15242b">

2023-09-19 17:00 UTC, mistryrn commented on apps/consent-ui/src/components/Home/Card/Card.tsx
> +			<h3>{translate('join-ohcrn')}</h3>
One thing to keep in mind with headings is that for accessibility best practices, we should try not to skip heading levels. In this case (the landing page), it looks like the `h1` is "Welcome to the OHCRN Registry", and I believe this "Join OHCRN" should be an `h2` instead of an `h3`.

Not a big deal! Just makes things smoother for screen readers that take a look at the page hierarchy. If you want to learn more, here's a couple links to skim through if you're keen :) 
- https://www.a11yproject.com/posts/how-to-accessible-heading-structure/
- https://www.w3.org/WAI/tutorials/page-structure/headings/

2023-09-19 17:03 UTC, mistryrn commented on apps/consent-ui/src/components/Home/Home.module.scss
Would it be possible to have the Footer not render below the fold if there's room? Not your fault, I think when we set up the scaffolding for the UI we made the Hero section fill the screen height on Desktop, but now that I see it in action I think it makes more sense to have it visible if the content height allows.

2023-09-19 17:24 UTC, mistryrn commented on apps/consent-ui/tailwind.config.js
**TL;DR: we need to investigate why our tailwind responsive breakpoint overrides aren't working, and then ask Patrick what to do in the awkward zone between tablet and desktop**

Something we might want to consult @patrickdsantos on – after looking at the responsiveness in action, things feel a bit weird between our md/tablet breakpoint and our desktop designs (from around `1024px` wide to `1179px`)

It looks like our desktop designs are at a width of 1440px (90rem) in Figma, so maybe they should kick in after the `xl` breakpoint and we use the tablet designs for md and lg?

For reference, the default Tailwind breakpoints are:
- sm: 640px
- md: 768px
- lg: 1024px
- xl: 1280px
- 2xl: 1536px

And we modified `sm` and `md` in our tailwind config, resulting in:
- sm: 480px
- md: 1024px
- lg: 1024px
- xl: 1280px
- 2xl: 1536px

However, now that I look at it, maybe the modification hasn't worked? `md` CSS appears to be kicking in at 768px right now. Might require some investigation to see what's going on with our tailwind overrides. @anncatton any thoughts?

Once the breakpoints are working as expected, we might want to do a screenshare with Patrick to show him how things look at the different sizes so he can determine how to proceed in those "awkward" widths

2023-09-19 17:28 UTC, mistryrn commented on apps/consent-ui/src/components/Home/Card/Card.tsx
> +			<CardButton Icon={PatientIcon} classes={styles.tabletCardBtn}>
Something that might be nice from a usability perspective for the CardButton – can the entire block be a link? Rather than having to click specifically on the "Register yourself today" text?

2023-09-19 17:43 UTC, alyssadsouza commented on apps/consent-ui/src/public/arrow.svg
I took a look at the designs for other pages and I do see the chevron arrow being used again. To be honest, I might have a preference for saving all the SVGs as components and not bother with saving them under `public` since they'd be automatically reusable and even if we don't customize them it still works as usual.

2023-09-19 17:51 UTC, anncatton commented on apps/consent-ui/src/public/arrow.svg
i would like to take advantage of the optimizing that's automatically available when we use next/image, where possible...so for things like the corporate logos in the header/footer elements i'd like to leave as is, if you're all on board. but for the reusable icons like we'd have in buttons etc i'm happy with the React SVG approach!

2023-09-19 17:53 UTC, alyssadsouza commented on apps/consent-ui/src/public/arrow.svg
makes sense!

2023-09-19 18:25 UTC, alyssadsouza commented on apps/consent-ui/src/components/Home/Home.module.scss
I think the issue with that before was that the webpage might be too short if there's not enough content on one page, and sorting out the height of the main page content got a bit tricky with the header and the footer. I think I can fix this with relative viewport heights by setting a relative min height for the header, footer, and main page content, I'll update it for the large media breakpoint since that's the only viewport that has the issue.

2023-09-19 20:15 UTC, alyssadsouza commented on apps/consent-ui/src/i18n/locales/en/footer.json
> +    "copyright": "© 2022 Ontario Hereditary Cancer Research Network. All rights reserved.",
yup, updating now!

2023-09-19 20:16 UTC, alyssadsouza commented on apps/consent-ui/src/components/Home/Card/Card.tsx
> +			<CardButton Icon={PatientIcon} classes={styles.tabletCardBtn}>
updated!

2023-09-19 20:17 UTC, alyssadsouza commented on apps/consent-ui/src/components/Home/Card/Card.tsx
> +			<h3>{translate('join-ohcrn')}</h3>
updated!

2023-09-20 21:12 UTC, alyssadsouza commented on apps/consent-ui/tailwind.config.js
was able to figure out why the breakpoints weren't working - after checking the docs looks like it was just supposed to be named `screens` in the tailwind config rather than `breakpoints`! updated the responsive styling based on our current custom breakpoints for now.

2023-09-21 13:27 UTC, anncatton requested changes
Looks good! Starting to look like a real website now 😁 Just a couple small changes requested. 
One thing i noticed when running it locally, the links in the footer seem to be left aligned on medium/small screens...i think on the responsive designs they were centered, but maybe that has changed since i first looked at them?

2023-09-21 15:00 UTC, alyssadsouza commented on apps/consent-ui/src/components/Header/Header.module.scss
> +    min-height: 10vh;
Hmm I haven't actually heard anything about the header yet... I updated it so the header stays the same size (10vh i.e. 10% of the viewport height) but that's open to changes!

2023-09-21 15:01 UTC, alyssadsouza commented on apps/consent-ui/src/components/Home/Card/Card.tsx
> +				path={'register'}
I'll update to name since it's consistent with LocalizedLink 👍

2023-09-21 15:13 UTC, alyssadsouza commented on apps/consent-ui/src/components/Home/Card/CardLink/index.tsx
> +	Icon: any;
updated to `React.ComponentType<any>`

2023-09-21 15:49 UTC, anncatton approved these changes
Awesome work, thanks @alyssadsouza ! 🎉 🚀 
I'm good with merging this once the PR for #58 is done and merged in `develop` so we have separate merge commits for each ticket

2023-09-21 22:15 UTC, mistryrn approved these changes
Great stuff!! Thanks for getting those changes in so quickly (and fixing our breakpoints 😅 ) Checked out and tested locally, looks **awesome** – some really nice subtle hover animations and things to tie it all together 😄 

As Ann said, good to merge this once the PR for #58 gets merged in!

2023-09-22 15:46 UTC, merged